### ISSUE TITLE
Pengumpulan TP dan Jurnal

### ISSUE THREAD

**Issue by SaidSamaludin** [D3IF-Cool/diskusi-mobpro#1]
permisi ka @zikrullah79 @elanadila6706162040 @anurulistiqamah @dzalfats @Aya1103 , ingin bertanya, untuk pengumpulan TP dan jurnal reponya yang dari dosen atau nnt kita buat repo sendiri ka ?

**Comment by anurulistiqamah** [comment]
Halo, said samaludin. 
Jadi untuk pengumpulan TP **wajib** pada halaman Wiki pada repo yang sudah dibuat sebelumnya (repo yang sudah dibuat sejak modul 3).
Untuk pengumpulan jurnal, buat branch baru dengan nama "jurnal07" di repo yang sama.
Terima kasih

**Comment by anurulistiqamah** [comment]
Halo, @SaidSamaludin 
Jadi untuk pengumpulan TP **wajib** pada halaman Wiki pada repo yang sudah dibuat sebelumnya (repo yang sudah dibuat sejak modul 3).
Untuk pengumpulan jurnal, buat branch baru dengan nama "jurnal07" di repo yang sama.
Terima kasih

**Comment by SaidSamaludin** [comment]
baik, terima kasih ka..
