### ISSUE TITLE
Permohonan Tutorial Pembahasan Jurnal

### ISSUE THREAD

**Issue by dodyrifkisuraya** [D3IF-Cool/diskusi-mobpro#10]
Selamat Sore, bapak/ibu dosen dan kakak kakak asprak. Sebelum Assesment 2 saya harap ada Tutorial Pembahasan Jurnal Sebelum-sebelumnya, dalam bentuk video atau tulisan(hemat kuota). Atau minimal Solusi kodingan juga boleh. Makasih

**Comment by zikrullah79** [comment]
bakal ada kok insyaAllah, dalam bentuk solusi kodingan. kmarin berhenti d jurnal 5 karena jadwal asprak yang begitu padat dan juga ada beberapa jurnal yang memakai kerjaan jurnal sebelumnya, takutnya solusi itu dipakai buat jurnal yang bersangkutan. jadi d pantengin aja.

**Comment by dodyrifkisuraya** [comment]
oke, makasih kak
