### ISSUE TITLE
Praktikum modul 10: Behind the scenes

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#12]
Pagi.. Praktikum kali ini kita akan melakukan sesi interaktif minim kuota dan diskusi via issue Github. Bagi yang sudah siap praktikum di komputer/laptopnya masing-masing, harap absen terlebih dahulu.

Format:
NIM - Nama - HADIR. Pertanyaan terkait materi (jika ada)

**Comment by fawwazammar** [comment]
6706181079 - M. Fathin Fawwaz Ammar - HADIR. Bagaimana cara mendapat akses internet di emulator andorid dari android studio ? Sudah mencari solusi tapi masih belum berhasil, biar ga ke jalanin di smartphone pribadi

**Comment by wahyunurrosyid** [comment]
6706180040 - Wahyu Nurrosyid - HADIR

**Comment by zhafirazahra** [comment]
6706184106 - Zhafira Zahra - HADIR

**Comment by rbudiawan** [comment]
@fawwazammar 
emulator mengambil koneksi internet dari komputer/laptop. Jadi kalau komputer/laptopnya terkoneksi internet, otomatis emulatornya juga terhubung ke internet. Untuk menguji koneksi internetnya, coba buka website pakai browser di emulator. Bisa diuji terlebih dahulu sebelum menjalankan aplikasi yang membutuhkan internet, karena bisa saja aplikasi yang butuh perbaikan. Bukan koneksi internetnya.

**Comment by fawwazammar** [comment]
> @fawwazammar
> emulator mengambil koneksi internet dari komputer/laptop. Jadi kalau komputer/laptopnya terkoneksi internet, otomatis emulatornya juga terhubung ke internet. Untuk menguji koneksi internetnya, coba buka website pakai browser di emulator. Bisa diuji terlebih dahulu sebelum menjalankan aplikasi yang membutuhkan internet, karena bisa saja aplikasi yang butuh perbaikan. Bukan koneksi internetnya.

Baik pak sudah jalan, Terima kasih Pak

**Comment by arindameika** [comment]
6706181039 - Arinda Meika Putri - HADIR

**Comment by Sivanurs** [comment]
6706184014 - Siva Nur Samrotissa'adah - HADIR

**Comment by Rizwan-4126** [comment]
6706174126 - Rizwan Ramadhan - HADIR

**Comment by melaniaindahsafitri** [comment]
6706184009 - Melania Indah Safitri - HADIR

**Comment by paulusnugroho123** [comment]
6706184033 - Paulus Agata Suryonugroho - HADIR

**Comment by dodyrifkisuraya** [comment]
6706181062 - Dody Rifki Suraya - HADIR

**Comment by nwfalia** [comment]
6706180110 - Nur Wakhidah Fitri Amalia - HADIR

**Comment by fadhilmuqsith** [comment]
6706184048 - Muh Fadhil Muqsith - HADIR

**Comment by viraashara** [comment]
6706180102 - Vira Ayu Indita Ashara - HADIR

**Comment by padhisayusuf** [comment]
6706184066 - Padhisa Yusuf Athif Maraya - HADIR

**Comment by yolandapurba148** [comment]
6706184135-Yolanda Stefani Putri Br Purba- HADIR

**Comment by mzakialkhairi13** [comment]
6706184117 - Muhammad Zaki Alkhairi - HADIR

**Comment by resie001** [comment]
6706184007 - Ade Resie M. S. - HADIR

**Comment by bacharuddinadieb** [comment]
6706180113 - Bacharuddin Adieb Pratama- HADIR
terdapat error
    com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
ketika mau meng insertAll data dari API

**Comment by ridloxyanuar** [comment]
6706174072 - RIDLO YANUAR - HADIR

**Comment by abdulharis00** [comment]
6706184052 - Abdul Haris - HADIR

**Comment by zakariaf05** [comment]
6706184074 - Zakaria Firdaus - HADIR

**Comment by farhanreninda** [comment]
6706184021 - Farhan Reninda Budiansyah - HADIR

**Comment by rbudiawan** [comment]
> 6706180113 - Bacharuddin Adieb Pratama- HADIR
> terdapat error
> com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
> ketika mau meng insertAll data dari API

Hal tersebut karena saat melakukan perubahan dari format json ke objek, tidak sesuai. Pastikan objeknya harus berisi ArrayList.. Karena JSON nya berupa JSONArray.

**Comment by aliyyulman** [comment]
6706184070 - Aliyyulman Jihan - HADIR
ijin bertanya pak, ketika saya mencoba Udacity bagian "Create a Worker" di file work/RefreshDataWork di Payload nya Unresolved .

**Comment by bacharuddinadieb** [comment]
> > 6706180113 - Bacharuddin Adieb Pratama- HADIR
> > terdapat error
> > com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
> > ketika mau meng insertAll data dari API
> 
> Hal tersebut karena saat melakukan perubahan dari format json ke objek, tidak sesuai. Pastikan objeknya harus berisi ArrayList.. Karena JSON nya berupa JSONArray.

Oke pak, sudah solved

**Comment by Restuananda** [comment]
6706184087 -- Restu ananda saputra

**Comment by hasbifm** [comment]
6706184091- Muhammad Faishal Hasbi- HADIR

**Comment by indraazimi** [comment]
> 
> 
> ijin bertanya pak, ketika saya mencoba Udacity bagian "Create a Worker" di file work/RefreshDataWork di Payload nya Unresolved .

@aliyyulman1999: contoh di Udacity menggunakan `WorkManager` versi 1.0.0-alpha11. Selanjutnya di versi [1.0.0-alpha12](https://developer.android.com/jetpack/androidx/releases/work#1.0.0-alpha12) kelas `Payload` ini ternyata diganti sama `Result`. This is a **breaking change**, makanya kita harus hindari penggunaan versi alpha/beta di production app.

Jadi codingnya sekarang kurang lebih jadi begini:
```kotlin
override suspend fun doWork(): Result {
    val database = getDatabase(applicationContext)
    val repository = VideosRepository(database)
    return try {
        repository.refreshVideos()
        Result.success()
    } catch (e: HttpException) {
        Result.retry()
    }
}
```
Referensi: [Create a background task](https://developer.android.com/topic/libraries/architecture/workmanager/basics#create_a_background_task)

**Comment by aliyyulman** [comment]
terimakasih banyak pak

**Comment by wisnusabani** [comment]
6706174107 - Wisnu Almi Pradya S - HADIR

**Comment by lukmannurwahidin02** [comment]
6706184125 - Lukman Nurwahidin - Hadir

**Comment by rooflesia** [comment]
6706180044 -Muhammad Rafli Naufal - Hadir

**Comment by anurulistiqamah** [comment]
Karena jadwal praktikum telah berakhir, kita tutup praktikum modul 10 ini. 
Jangan lupa hari ini hari terakhir update nomor handphone di igracias pakai Telkomsel, biar dapat subsidi kuota hehe. Kesehatan dan semangatnya tolong dijaga juga ya #dirumahaja. 
Trims. Wassalamualaikum

**Comment by dodyrifkisuraya** [comment]
@indraazimi Tanya Pak.
Cara filter data JSON gimana pak? misal untuk nampilin miwok categori yg beda dan nampilin miwok kategori sama

**Comment by indraazimi** [comment]
> Cara filter data JSON gimana pak? misal untuk nampilin miwok categori yg beda dan nampilin miwok kategori sama

Yang difilter bukan JSON nya @dodyrifkisuraya. JSON nya kan udah kita masukin ke database (offline cache). Jadi yang difilter database nya aja, biar lebih gampang.

Untuk nampilin kategori pake query SELECT DISTINCT atau pake GROUP BY juga boleh. Untuk nampilin daftar kata di kategori tinggal query SELECT ... WHERE category = ?

**Comment by andiddng** [comment]
6706184003-Andi Muh Gilang R-Hadir

**Comment by dodyrifkisuraya** [comment]
> > Cara filter data JSON gimana pak? misal untuk nampilin miwok categori yg beda dan nampilin miwok kategori sama
> 
> Yang difilter bukan JSON nya @dodyrifkisuraya. JSON nya kan udah kita masukin ke database (offline cache). Jadi yang difilter database nya aja, biar lebih gampang.
> 
> Untuk nampilin kategori pake query SELECT DISTINCT atau pake GROUP BY juga boleh. Untuk nampilin daftar kata di kategori tinggal query SELECT ... WHERE category = ?

Ok pak makasih

**Comment by dodyrifkisuraya** [comment]
@indraazimi Pak tanya.
 Saya udah pake versi work manager sama dengan udacity tapi ga ada object "payload". dan adanya malah "result". Gimana itu pak?

**Comment by indraazimi** [comment]
> Saya udah pake versi work manager sama dengan udacity tapi ga ada object "payload". dan adanya malah "result". Gimana itu pak?

@dodyrifkisuraya: Masak sih? Coba build.gradle nya tulis di sini.
