### ISSUE TITLE
communication not permitted

### ISSUE THREAD

**Issue by alfathabibi** [D3IF-Cool/diskusi-mobpro#13]
bismillah
punten pak mau nanya 
pada saat saya membuat aplikasi bahasa miwok modul connect to the internet 
ketika saya run aplikasinya di avd : API 22 berhasil tapi pada saat saya run aplikasinya di hp saya : Android 9 pesannya CLEARTEXT communication not permitted. Saya telah memberikan izin internet juga di manifestnya
@rbudiawan  @indraazimi

**Comment by indraazimi** [comment]
Masalah ini udah pernah dibahas minggu lalu. Cek di sini: https://github.com/D3IF-Cool/diskusi-mobpro/issues/4#issuecomment-606343522

**Comment by alfathabibi** [comment]
Baik pak terima kasih
