### ISSUE TITLE
Penggunaan asDomainModel() di repository

### ISSUE THREAD

**Issue by azmirizkifar20** [D3IF-Cool/diskusi-mobpro#14]
Assalamu'alaikum pak/bu dan juga kakak asprak, selamat sore.
Saya ingin bertanya terkait penggunaan asDomainModel() di bagian repository, itu fungsi utamanya untuk apa ya? dan ketika saya mau implementasikan ke kodingan saya kenapa jadi merah ya seperti gambar ini :

![image](https://user-images.githubusercontent.com/43155964/78653910-ff0f5a80-78ed-11ea-83c8-75d48cbe502a.png)

Ini bagian DatabaseEntities.kt nya, karena ini relate dengan kodingan yang di atas kalau di tutorial yang ada di udacity : 
![image](https://user-images.githubusercontent.com/43155964/78654005-2108dd00-78ee-11ea-8e03-f06aae84e59e.png)

Terimakasih pak/bu dan kakak asprak. 
@indraazimi @anurulistiqamah @zikrullah79 @Aya1103 @elanadila6706162040

**Comment by zikrullah79** [comment]
hai azmi, di screenshot yang ini bisa diperhatikan 

![Capture](https://user-images.githubusercontent.com/30121256/78662356-6f23dd80-78fa-11ea-8f14-376b759ee2dd.PNG)
![Captu2re](https://user-images.githubusercontent.com/30121256/78662381-7a770900-78fa-11ea-9f1a-158c41ab2bf3.PNG)

nilai keluaran database.miwokDao.getMiwok() adalah List dari MiwokDatabase sedangkan .asDomainModel() ada di List dari MiwokDatabaseModel. mungkin bisa diperhatikan lagi fungsi database.miwokDao.getMiwok().

**Comment by indraazimi** [comment]
Wa'alaikum salam.. Klo di tutorial Udacity, `asDomainModel` adalah sebuah [Kotlin extension function](https://kotlinlang.org/docs/tutorials/kotlin-for-py/extension-functionsproperties.html) yang berguna untuk mengubah `List<DatabaseVideo>` menjadi `List<Video>`. Coba perhatikan lagi definisinya ini:
```kotlin
fun List<DatabaseVideo>.asDomainModel(): List<Video> {
    ...
}
```

Kemudian coba perhatikan juga coding di bagian repository ini:
```kotlin
val videos: LiveData<List<Video>> =
        Transformations.map(database.videoDao.getVideos()) {
    it.asDomainModel()
}
```

`it` di situ merujuk kepada hasil dari `database.videoDao.getVideos()` yaitu `List<DatabaseVideo>` (bisa dicek di bagian [definisi Dao](https://github.com/udacity/andfun-kotlin-dev-bytes/blob/master/app/src/main/java/com/example/android/devbyteviewer/database/Room.kt#L27)). Tipe datanya cocok, sehingga di tutorial Udacity tersebut tidak ada masalah.

Mengapa codingan @azmirizkifar20 terjadi error? Karena **tipe datanya tidak cocok**, seperti yang telah ditandai Kak @zikrullah79 di atas.

**Comment by azmirizkifar20** [comment]
baik pak @indraazimi , kak @zikrullah79  sudah bisa.. terimakasih pak

**Comment by indraazimi** [comment]
Alhamdulillah.. Klo gitu Bpk close ya issue nya.
