### ISSUE TITLE
Force close pada saat wifi dan data seluler dimatikan

### ISSUE THREAD

**Issue by irgiahmadm** [D3IF-Cool/diskusi-mobpro#15]
Assalamualaikum pak @rbudiawan @indraazimi  dan kaka asprak @zikrullah79 @elanadila6706162040 , mau bertanya perihal jurnal modul 10, saya sudah coba materi behind the scene sampai WorkManager. lalu ketika menjalankan aplikasi pertama kali berjalan sesuai yang di inginkan list video muncul, akan tetapi ketika wifi dan data seluler dimatikan aplikasi muncul sebentar beserta datanya lalu tiba tiba force close tanpa keterangan error yang jelas hanya muncul FatalExceptionMain, apakah memang begitu harusnya ? jika iya, apakah itu disebabkan oleh fungsi dibawah ini :

![image](https://user-images.githubusercontent.com/29327450/78686420-2fbab880-791d-11ea-8fd4-fecfac143f78.png)

apakah .setRequireNetworkType(NetworkType.Metered) mempengaruhi ?

**Comment by indraazimi** [comment]
Harusnya nggak force close. Dicek aja di logcat errornya apa. Perhatikan bagian "cause by" nya.. Klo bingung baca logcat, bisa tuliskan stacktrace error nya di sini.

Mengenai `NetworkType` baca aja dokumentasinya di sini: https://developer.android.com/reference/androidx/work/NetworkType

**Comment by irgiahmadm** [comment]
di Logcat ga munculin errror caused by apa, jadi hanya munculin error kaya gini pak:
FATAL EXCEPTION MAIN

skenario error nya :

status dari wifi dan data seluler nyala.

list muncul,

aplikasi di keluarkan lalu di kill,

status wifi dan data seluler dimatikan,

buka ulang aplikasi,

list muncul sebentar lalu keluar tiba tiba dari aplikasi,

logcat memunculkan error Fatal Exception Main saja tanpa keterangan caused By :

**Comment by irgiahmadm** [comment]
begini pak @indraazimi Logcat nya

![image](https://user-images.githubusercontent.com/29327450/78693323-4a912b00-7925-11ea-9f0b-09495c63155e.png)

itu yang sudah saya implementasiin ke jurnal
-------------------------------------------------------------------------------------------------------------
yang dibawah ini yang contoh dari udacity nya pak

![image](https://user-images.githubusercontent.com/29327450/78693646-be333800-7925-11ea-848d-c45cbfa9a891.png)

**Comment by irgiahmadm** [comment]
[SOLVED] kurang try catch pada viewmodel ketika me refresh video
