### ISSUE TITLE
Praktikum modul 10: Behind the scene

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#16]
Pagi.. di jam praktikum rutin ini, kita mulai sesi interaktif minimum kuota. Untuk yang sudah standby di depan laptopnya, boleh menuliskan nim nama HADIR dan juga pertanyaan (jika ada).

**Comment by Azizalfauzi** [comment]
Aziz Alfauzi - 6706180067 Hadir

**Comment by irgiahmadm** [comment]
6706180041-Irgi Ahmad Maulana-Hadir

**Comment by winadarma** [comment]
6706184107-Wina Darma Rahmah-Hadir

**Comment by KharisZakaria** [comment]
6706180122 - Kharis Zakaria  - HADIR

**Comment by FadilIlhamm** [comment]
6706184018-Fadil Ilham Muharram-Hadir

**Comment by banyunurwishal** [comment]
6706184075-Banyu Nurwishal Luthfiansyam-Hadir

**Comment by haidarrp** [comment]
6706180130- Haidar Rasyid - Hadir

**Comment by annisanurfauziyah** [comment]
6706184099 - Annisa Nur Fauziyah - HADIR

**Comment by MaulidiyahZuhdi** [comment]
6706184011-Maulidiyah Zuhdi

**Comment by ShakilaZahraP** [comment]
6706184103-Shakila Zahra Previa-HADIR

**Comment by Sayyid01** [comment]
67067181063- Naufal Sayyid Furqoon - Hadir

**Comment by dickymujantara** [comment]
6706181088 - Muhammad Dicky Mujantara - HADIR

**Comment by titanhafizh** [comment]
6706184030 - Titan Hafizh Surya Kusuma - HADIR

**Comment by fikri0511** [comment]
6706181071 - Muhammad Fikri Fadilah - HADIR

**Comment by zia123123** [comment]
6706184114 - Zia Muhammad Najieb - HADIR

**Comment by azmirizkifar20** [comment]
6706184055-Muhamad Azmi Rizkifar-Hadir

**Comment by mmuhammadarief** [comment]
6706184045 - Muhammad Arief Fauzan - Hadir

**Comment by naufal7567** [comment]
6706181022 - Muhammad Naufal Rabbani - Hadir

**Comment by fhmsyhd** [comment]
6706184097 - Fahmi Imam Syuhada - Hadir

**Comment by MaulidiyahZuhdi** [comment]
6706184011-Maulidiyah Zuhdi - HADIR

**Comment by alfathabibi** [comment]
6706183049 - Muhammad Alfath Abibi - Hadir

**Comment by sheillya** [comment]
6706184053 - ST Sheillya Pradina - Hadir

**Comment by dewaadityaarmanda** [comment]
6706184004 - Dewa Aditya Armanda - Hadir

**Comment by Nurilfebris** [comment]
6706180126-nuril febri s-Hadir

**Comment by muhamadanasmustopa** [comment]
6706184026-Muhamad Anas Mustopa-Hadir

**Comment by transylvanioalfza** [comment]
6706184118 - M Transylvanio Alfarezha - Hadir

**Comment by haikalgakbar** [comment]
6706181059 - Haikal Gibran Akbar - Hadir

**Comment by RendiWinurdani** [comment]
6706184084 - Rendi Winurdani - HADIR

**Comment by miaanjani** [comment]
6706184111 - Mia Anjani Darojatun Salam - HADIR

**Comment by alfathabibi** [comment]
Punten pak saya mau bertanya, kalau coroutine scop yang  digunakan tidak di eksekusi itu kenapa yah pak @rbudiawan

**Comment by alfathabibi** [comment]
![Capture](https://user-images.githubusercontent.com/60532478/78736393-38d87380-7977-11ea-85cf-f34dd215ac95.PNG)

**Comment by alfathabibi** [comment]
code yang di eksekusi hanya sampai di _status.value = "Success"
yang didalam tag viewModelScope.launch tidak di jalankan pak

**Comment by ffaathirullah** [comment]
6706184111 - Fachrul Faathirullah - HADIR

**Comment by AnderaFamuzia** [comment]
6706184034 - Muhamad Andera Famuzia - HADIR

**Comment by rbudiawan** [comment]
> Punten pak saya mau bertanya, kalau coroutine scop yang digunakan tidak di eksekusi itu kenapa yah pak @rbudiawan

@alfathabibi hmmm, saya belum tahu permasalahannya di mana. Karena kodenya terlihat oke untuk saya. Coba pastikan scope dari viewmodel, merupakan scope couroutine dari supervisorJob dan juga Dispatcher.Main. 

Lalu, untuk membuktikan berjalan (atau melihat eksekusi program), bisa memberikan kode Log di beberapa baris kode dalam method itu. Jadi tidak dilihat dari _status nya saja.
