### ISSUE TITLE
Praktikum Modul 10: Behind The Scene

### ISSUE THREAD

**Issue by cahyana78** [D3IF-Cool/diskusi-mobpro#17]
Dear all,  ini adalah sesi interaktif minimum kuota. Untuk yang sudah standby, bisa menuliskan NIM, Nama, HADIR dan juga pertanyaan (jika ada).

**Comment by ahmadridhoiwananda** [comment]
6706184020 - Ahmad Ridho Iwananda - HADIR

**Comment by fhmbyn** [comment]
6706184095 - FAHMI AJI BAYYAN DHIYA - HADIR

**Comment by farhanshofwani1159** [comment]
6706184047 - Farhan Shofwani - HADIR

**Comment by ikhbalrz** [comment]
6706180124 - Muhammad Ikhbal Rezanika - HADIR

**Comment by ahmadaamin12** [comment]
6706184078 - Ahmad Amin - HADIR

**Comment by adammaulana06** [comment]
6706184057 - Adam Maulana - HADIR

**Comment by ridhobahar1** [comment]
6706184065 - Ridho Prawira Bahari - HADIR

**Comment by vironika07** [comment]
6706184105 - Vironika Ayuning Tiyas - HADIR

**Comment by literally1d** [comment]
6706180024 - Wandi Yusuf Kurniawan - HADIR

**Comment by nurhidayahputeri** [comment]
6706184101 - Nurhidayah Puteri - HADIR

**Comment by deltaputrii** [comment]
6706184109 - Delta Putri Dewanda - HADIR

**Comment by syahudanahatmasuni** [comment]
6706181120 - HNW Syahuda Nahatmasuni - HADIR

**Comment by andibajangnurulizza** [comment]
6706184134 - Andi Bajang Nurul Izza Hadir

**Comment by hafidsuhanizar09** [comment]
6706183043 - Hafid Suhanizar - HADIR

**Comment by muhamadadjis2** [comment]
6706180073 M Piniki Adjis HADIR

**Comment by PutraBudiansyah** [comment]
6706184090 Putra Budiansyah HADIR

**Comment by shalsaazzahra11** [comment]
6706184038 - Putri Shalsabilla Azzahra - HADIR

**Comment by MuhammadArifin22** [comment]
6706184128 - Muhammad Arifin "HADIR"

**Comment by rikkylingga55** [comment]
6706180032 - Rikky Valentino Lingga - HADIR

**Comment by AndiezSatria** [comment]
6706184028 - Mohammad Andiez Satria Permana HADIR

**Comment by cahyana78** [comment]
Oh iya, untuk pertanyaan, tolong sampaikan di repo Diskusi Mobpro ya, agar terpantau

**Comment by alifiaulilalbab** [comment]
6706184077-Alifia Ulil Albab HADIR

**Comment by Farhancaandra** [comment]
6706184132-Farhan Candra Nugraha HADIR

**Comment by cahyana78** [comment]
Yang belum kelihatan sampai saat ini:
- BAGUS TETUKO 
- DINDA ANUGRAHENI S. DWI PUTRI
- HAFID SUHANIZAR
- FACHRAN SETIAWAN WARDI
- NANDA PUTRI MILANIA
- ARJUN IZA MAHENDRA
- DANY RAZZAQ FARINO

Tidak ada yang sudah hadir, tapi saya tulis di atas ini kan?

**Comment by hafidsuhanizar09** [comment]
> Yang belum kelihatan sampai saat ini:
> 
> * BAGUS TETUKO
> * DINDA ANUGRAHENI S. DWI PUTRI
> * HAFID SUHANIZAR
> * FACHRAN SETIAWAN WARDI
> * NANDA PUTRI MILANIA
> * ARJUN IZA MAHENDRA
> * DANY RAZZAQ FARINO
> 
> Tidak ada yang sudah hadir, tapi saya tulis di atas ini kan?

Saya hadir Bu

**Comment by hafidsuhanizar09** [comment]
> 6706183043 - Hafid Suhanizar - HADIR

Ini Bu

**Comment by cahyana78** [comment]
> > 6706183043 - Hafid Suhanizar - HADIR
> 
> Ini Bu

Ah iya, maaf, ikut terambil namanya... Sudah dimasukkan Hafid...

**Comment by hafidsuhanizar09** [comment]
> > > 6706183043 - Hafid Suhanizar - HADIR
> > 
> > 
> > Ini Bu
> 
> Ah iya, maaf, ikut terambil namanya... Sudah dimasukkan Hafid...

Oke terima kasih Bu

**Comment by BagusTetuko** [comment]
6706180086 - BAGUS TETUKO - HADIR
