### ISSUE TITLE
Permohonan Perpanjangan Waktu Pengumpulan Jurnal 8 Mobpro

### ISSUE THREAD

**Issue by yudhaprimadiansyah** [D3IF-Cool/diskusi-mobpro#2]
Assalamualaikum Wr. Wb, Selamat siang, salam sejahtera bagi kita semua, yang saya hormati, bapak/ibu dosen dan kakak kakak asprak @anurulistiqamah @zikrullah79 @Aya1103 @elanadila6706162040 , perkenalkan , saya yudha primadiansyah (NIM : 6706180083) dari kelas D3IF-42-02. mohon maaf sebelumnya,   saya mewakili beberapa rekan saya yang menemui kendala saat pengerjaan jurnal mobpro yang baru kami dapatkan hari ini pukul 9 pagi, dikarenakan wabah covid19 semakin meluas, termasuk di tempat saya sendiri, disekitar saya sudah ada 2 suspect dalam radius 200 meter yang memaksa saya untuk berdiam diri di rumah dengan koneksi internet seadanya dan laptop yang tidak memadai, yang tidak cukup untuk mempelajari materi yang membutuhkan banyak kuota serta, penggunaan android studio yang membutuhkan internet dan tenaga komputasi yang tidak kecil, kami memohon pemakluman kepada bapak/ibu dan kakak asprak untuk memperpanjang masa pengumpulan jurnal yang menurut kami terlalu singkat untuk dipelajari dan dikerjakan sendiri. dengan segala hormat dan permintaan maaf saya ucapkan terimakasih.

**Comment by fawwazammar** [comment]
Saya juga hampir memiliki kendala yang sama tentang internet, 
dan dalam pembelajaran daring seperti ini yang secara tidak langsung memaksakan bagi setiap mahasiswa untuk belajar mandiri (otodidak), memberi terkanan tersendiri bagi saya yang kurang mampu (membutuhkan cukup waktu) untuk memahami materi dengan tanpa bantuan pemahaman orang lain.
Saya sangat berterima kasih bila ada video pembahasan dengan bahasa Indonesia dan mudah dipahami tentang materi di Udacity dari pihak dosen maupun asprak. Karena dimodul ini saya merasa terkadang ada file yang ada tiba tiba tanpa tahu asalnya dari mana.
dan mungkin seperti yang diharapkan temen saya dengan menambah waktu pengerjaan cukup membuat kami lebih tenang dengan tugas.
Mohon maaf apa bila ada salah kata dari saya sendiri
Terima Kasih :)

**Comment by elanadila** [comment]
Waalaikumsalam, dek @yudhaprimadiansyah @fawwazammar.
Mohon maaf untuk penambahan waktu kami anggap tidak adil bagi kelas sebelumnya, jadi tidak ada penambahan waktu. Kumpulkan saja seadanya sebelum jadwal yg ditentukan ga ada tambahan. 
Untuk TP dan jurnal modul 8 ini ada keringanan yaitu dibebaskan bagi peserta Google FDP lulusan Android Pemula dan tetap tidak ada penambahan waktu bagi yang tidak lulus.

**Comment by indraazimi** [comment]
@yudhaprimadiansyah dkk, baru mempelajari materi Mobpro di hari praktikum adalah strategi yang keliru. Baiknya mempelajari materinya dicicil. Jadi habis praktikum modul 7, besoknya langsung aja dibuka materi modul 8-nya. Kan bisa sebenarnya..? Jika ada yang **kurang dimengerti terkait materi**, langsung aja buat issue baru, nanti permasalahannya akan dibahas oleh tim dosen dan asprak.

Jadi ketika soal jurnalnya terbit, kalian udah siap dengan materinya.. Perlu diingat, biasanya waktu pengerjaan jurnal ini hanya 2 jam, tapi dengan model praktikum online sekarang, waktu pengerjaan jurnalnya menjadi jauh lebih lama. Hitung aja sendiri, dari jam 9 pagi soal diberikan, sampai jam 23:59, ada berapa jam? Masih kurang? Mau ditambah jadi berapa lama lagi?

**Comment by indraazimi** [comment]
@fawwazammar, terkait koneksi internet yang terbatas, jika tidak bisa membuka Udacity yang pembelajarannya berbasis video, kamu bisa buka versi tutorial yang lebih ringan di sini: [Android Kotlin Fundamentals CodeLabs](https://codelabs.developers.google.com/android-kotlin-fundamentals/).. Kemudian, sebelum membuka starter code di Android Studio, bisa dikonfigurasi dulu Gradle-nya biar nggak banyak download. Insya Allah dalam waktu dekat Bpk buatkan tutorialnya.

Terkait materi yang ber-Bahasa Inggris, Bpk sering bilang, kan kita _world class university_. Jadi harus bisa menyesuaikan ya.. Konten ber-Bahasa Inggris itu baik buatmu. Apalagi di era globalisasi seperti sekarang. Nggak bisa Bahasa Inggris, akan kalah saing di dunia kerja nantinya.

**Comment by yudhaprimadiansyah** [comment]
Terimakasih atas konfirmasi dan masukan dari bapak/ibu dosen dan kakak asprak, mohon maaf jika cara kami keliru dalam menyesuaikan kondisi saat ini, dari kondisi ini kami memetik pelajaran untuk kedepannya supaya kami lebih mempersiapkan diri dan setelah berdiskusi kami telah menemukan cara belajar terbaik sebagai langkah menyesuaikan diri dengan pembelajaran online ini, terima kasih banyak pak atas masukannya , dengan menaruh rasa hormat dan permintaan maaf , saya ucapkan terima kasih

**Comment by fawwazammar** [comment]
Mungkin akan sangat membantu meringankan beban internet dengan adanya video konfigurasi Gradle tersebut. Saya akan menantikan dan segera mengimplementasikannya demi memperlancar proses pembelajaran daring.

dan konten bahasa Inggris saya akan segera mencoba menyesuaikannya,  semoga dengan keadaan seperti ini saya dapat mengimplementasikan world class university yang sebenarnya.

dan terakhir saya mengucapkan terima kasih banyak dan mohon maaf telah mengganggu waktu istirahat bapak dosen dan kakak kakak asprak semuanya.
