### ISSUE TITLE
Praktikum Modul 11: Designing for everyone

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#21]
Pagi semua, praktikum kali ini kita akan melakukan sesi interaktif minimum kuota.

Silahkan tuliskan nim-nama-HADIR dan juga pertanyaan (jika ada).

**Comment by farhanreninda** [comment]
6706184021 - Farhan Reninda Budiansyah - HADIR

**Comment by paulusnugroho123** [comment]
6706184033-Paulus Agata Suryonugroho-HADIR

**Comment by abdulharis00** [comment]
6706184052- Abdul Haris - HADIR

**Comment by lukmannurwahidin02** [comment]
6706184125 - Lukman Nurwahidin - HADIR

**Comment by mzakialkhairi13** [comment]
6706184117 - Muhammad Zaki Alkhairi - HADIR

**Comment by Sivanurs** [comment]
6706184014 - Siva Nur Samrotissa'adah - HADIR

**Comment by Rizwan-4126** [comment]
6706174126 - Rizwan Ramadhan - HADIR

**Comment by viraashara** [comment]
6706180102 - Vira Ayu Indita Ashara - HADIR

**Comment by fadhilmuqsith** [comment]
6706184048 - Muh Fadhil Muqsith - HADIR

**Comment by utong30** [comment]
6706184058 - Tamu Umbu Hunga Wohangara - HADIR

**Comment by wisnusabani** [comment]
6706174107 - Wisnu Almi Pradya.S - HADIR

**Comment by arindameika** [comment]
6706181039 - Arinda Meika Putri - HADIR

**Comment by melaniaindahsafitri** [comment]
6706184009 - Melania Indah Safitri - HADIR

**Comment by bacharuddinadieb** [comment]
6706180113 - Bacharuddin Adieb Pratama - HADIR

**Comment by yudhaprimadiansyah** [comment]
6706180083 - Yudha Primadiansyah - Hadir

**Comment by nwfalia** [comment]
6706180110 - Nur Wakhidah Fitri Amalia - Hadir

**Comment by fawwazammar** [comment]
6706181079 - M. Fathin Fawwaz Ammar - Hadir

**Comment by zhafirazahra** [comment]
6706184106 - Zhafira Zahra - Hadir

**Comment by resie001** [comment]
6706184007 - Ade Resie M S - HADIR

**Comment by Restuananda** [comment]
6706184087 - Restu ananda saputra - Hadir

**Comment by aliyyulman** [comment]
6706184070 - Aliyyulman Jihan - HADIR

**Comment by padhisayusuf** [comment]
6706184066 - Padhisa Yusuf Athif Maraya - HADIR

**Comment by dodyrifkisuraya** [comment]
6706181062 - Dody Rifki Suraya - HADIR

**Comment by yolandapurba148** [comment]
6706184135-Yolanda Stefani Putri - HADIR

**Comment by wahyunurrosyid** [comment]
6706180040-Wahyu Nurrosyid-HADIR

**Comment by rooflesia** [comment]
6706180044 - Muhammad Rafli Naufal - Hadir

**Comment by ridloxyanuar** [comment]
6706174072 - RIDLO YANUAR - HADIR

**Comment by andiddng** [comment]
6706184003 - Andi Muh Gilang R - Hadir

**Comment by anurulistiqamah** [comment]
Kita tutup ya praktikum sesi interaktif minimum kuota ini. 
Dengan berakhirnya modul ini, maka berakhir pula kegiatan praktikum Mobpro Dasar utk semester ini. Mohon maaf bila ada salah kata dari kami. Terima kasih untuk semuanya. Wassalamualaikum

**Comment by hasbifm** [comment]
6706184091_Muhammad faishal hasbi_Hadir
