### ISSUE TITLE
Aplikasi force close ketika menambahkan kodingan dark mode

### ISSUE THREAD

**Issue by literally1d** [D3IF-Cool/diskusi-mobpro#22]
Assalamu'alaikum, pak @indraazimi , pak @rbudiawan , bu @cahyana78 , dan kakak-kakak asprak @anurulistiqamah @zikrullah79 @Aya1103 @elanadila6706162040 @dzalfats . Saya ingin bertanya perihal jurnal 11 ini. Ketika saya menambahkan kodingan dark mode dan menjalankannya, aplikasi langsung force close dan error di kodingan ini:

```
NavigationUI.setupActionBarWithNavController(this, navController) //error di sini
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
```

Itu kira-kira kenapa bisa seperti itu? Mohon penjelasannya, terima kasih...

**Comment by indraazimi** [comment]
Wa'alaikum salam. Error nya apa @literally1d? Coba cek logcat nya dulu. Klo nggak tau pesan error nya apa, Bpk nggak bisa menerka solusinya.

**Comment by literally1d** [comment]
Tunggu sebentar, pak @indraazimi ...
![Screenshot (76)](https://user-images.githubusercontent.com/49407384/79248901-aa984c00-7ea6-11ea-940b-940306944a8f.png)
Apakah karena perubahan isi styles.xml (`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">` dan menambahkan item warna/text) bisa mempengaruhi isi activity_main.xml?
![Untitled](https://user-images.githubusercontent.com/49407384/79249918-2d6dd680-7ea8-11ea-8508-8f8affff73d0.png)

**Comment by indraazimi** [comment]
Coba dibaca logcat baris pertamanya. Errornya kan **Caused by: NullPointerException**. Di logcat itu kelihatan jelas bahwa `ActionBar` nya nggak ada (null). Kok bisa? Karena tema yang @literally1d pakai `DayNight.NoActionBar`.

Trus gimana caranya biar nggak error? Ya `ActionBar` nya dibuat ada. Pakai tema yang ada `ActionBar` nya, atau tetap pakai tema sekarang tapi tambahkan `Toolbar` sebagai `ActionBar`.

**Comment by literally1d** [comment]
Baik, akan saya coba...
![image](https://user-images.githubusercontent.com/49407384/79294253-e3b0da80-7eff-11ea-89ce-8373e768cbbd.png)
![Screenshot_2020-04-15-09-48-48-80_5fbe281abc5dcc570ee3287255e9420d](https://user-images.githubusercontent.com/49407384/79294316-0511c680-7f00-11ea-87b9-e0bf4f1f0203.png)
Sekarang aplikasi sudah berjalan dengan lancar, terima kasih pak @indraazimi , terima kasih semuanya...

**Comment by indraazimi** [comment]
Alhamdulillah.. Klo gitu issue nya Bpk close ya!
