### ISSUE TITLE
Praktikum Modul 11: Designing for Everyone

### ISSUE THREAD

**Issue by cahyana78** [D3IF-Cool/diskusi-mobpro#23]
Dear all, hari ini kita sudah sampai pada praktikum terakhir Mobpro, alhamdulillah :) Seperti sebelumnya, ini adalah sesi interaktif minim kuota.

Silahkan menuliskan NIM, nama dan "HADIR", juga pertanyaan jika ada

**Comment by ridhobahar1** [comment]
6706184065 - Ridho Prawira Bahari - HADIR

**Comment by MuhammadArifin22** [comment]
6706184128 - Muhammad Arifin - HADIR

**Comment by ahmadaamin12** [comment]
6706184078 - Ahmad Amin - HADIR

**Comment by andibajangnurulizza** [comment]
6706184134 Andi Bajang Nurul Izza - HADIR

**Comment by nurhidayahputeri** [comment]
6706184101 - Nurhidayah Puteri - HADIR

**Comment by vironika07** [comment]
6706184105 - Vironika Ayuning Tiyas - HADIR

**Comment by BagusTetuko** [comment]
6706180086 - BAGUS TETUKO - HADIR

**Comment by hafidsuhanizar09** [comment]
6706183043 - Hafid Suhanizar - HADIR

**Comment by shalsaazzahra11** [comment]
6706184038 - Putri Shalsabilla Azzahra - HADIR

**Comment by PutraBudiansyah** [comment]
6706184090- Putra Budiansyah - HADIR

**Comment by muhamadadjis2** [comment]
6706180073 - M Pinki Adjis - HADIR

**Comment by ahmadridhoiwananda** [comment]
6706184020 - Ahmad Ridho Iwananda - HADIR

**Comment by Farhancaandra** [comment]
6706184132 - Farhan Candra Nugraha - HADIR

**Comment by farhanshofwani1159** [comment]
6706184047 - Farhan Shofwani - HADIR

**Comment by ikhbalrz** [comment]
6706180124 - Muhammad Ikhbal Rezanika - HADIR

**Comment by fhmbyn** [comment]
6706184095 - FAHMI AJI BAYYAN DHIYA - HADIR

**Comment by rikkylingga55** [comment]
6706180032 - Rikky Valentino Lingga - HADIR

**Comment by TLredmagic** [comment]
6706184061 - Dany Razzaq Farino - HADIR

**Comment by adammaulana06** [comment]
6706184057 - Adam Maulana - HADIR

**Comment by AndiezSatria** [comment]
6706184028 - Mohammad Andiez Satria Permana - HADIR

**Comment by deltaputrii** [comment]
6706184109 - Delta Putri Dewanda - HADIR

**Comment by alifiaulilalbab** [comment]
6706184077 - Alifia Ulil Albab - HADIR

**Comment by literally1d** [comment]
6706180024 - Wandi Yusuf Kurniawan - HADIR

**Comment by cahyana78** [comment]
Baik, jadi yang tidak hadir:
- DINDA ANUGRAHENI S. DWI PUTRI
- HNW SYAHUDA NAHATMASUNI
- FACHRAN SETIAWAN WARDI
- NANDA PUTRI MILANIA
- ARJUN IZA MAHENDRA

Ada yang saya salah?

**Comment by fachranwardi10** [comment]
6706184001 - FACHRAN SETIAWAN WARDI - HADIR.
Mohon Maaf bu saya baru sadar issuenya di "diskusi" setelah diberitahu teman, saya dari tadi stad by di "jurnal"
