### ISSUE TITLE
Praktikum modul 11: Designing for everyone

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#24]
Pagi semua.. di sini kita akan melakukan sesi interaktif minimal kuota. Silahkan tulis nim-nama-HADIR dan juga pertanyaan untuk modul ini (jika ada).

**Comment by titanhafizh** [comment]
6706184030-Titan Hafizh Surya Kusuma-HADIR

**Comment by KharisZakaria** [comment]
6706180122 - Kharis Zakaria - HADIR

**Comment by fikri0511** [comment]
6706181071 -Muhammad Fikri Fadilah -  HADIR

**Comment by zia123123** [comment]
6706184114 - Zia Muhammad -Hadir

**Comment by transylvanioalfza** [comment]
6706184118 - M Transylvanio Alfarezha - HADIR

**Comment by winadarma** [comment]
6706184107 - Wina Darma Rahmah - HADIR

**Comment by annisanurfauziyah** [comment]
6706184099 - Annisa Nur Fauziyah - HADIR

**Comment by sheillya** [comment]
6706184053 - ST Sheillya Pradina - Hadir

**Comment by banyunurwishal** [comment]
6706184075 - Banyu Nurwishal Luthfiansyam - Hadir

**Comment by haidarrp** [comment]
6706180130 - Haidar Rasyid - Hadir

**Comment by ShakilaZahraP** [comment]
6706184103 - Shakila Zahra Previa - Hadir

**Comment by miaanjani** [comment]
6706184111 - Mia Anjani Darojatun Salam - Hadir

**Comment by mmuhammadarief** [comment]
6706184045 - Muhammad Arief Fauzan - Hadir

**Comment by MaulidiyahZuhdi** [comment]
6706184011 - Maulidiyah Zuhdi - Hadit

**Comment by MaulidiyahZuhdi** [comment]
6706184011 - Maulidiyah Zuhdi - Hadir

**Comment by Nurilfebris** [comment]
6706180126 - Nuril febri setiyawan - Hadir

**Comment by FadilIlhamm** [comment]
6706184018- Fadil Ilham Muharram - hadir

**Comment by azmirizkifar20** [comment]
6706184055 - Muhammad Azmi Rizkifar - Hadir

**Comment by Azizalfauzi** [comment]
6706180067-Aziz Alfauzi -Hadir

**Comment by Sayyid01** [comment]
6706181063-Naufal Sayyid Furqoon-HADIR

**Comment by ffaathirullah** [comment]
6706181008 - Fachrul Faathirullah

**Comment by ffaathirullah** [comment]
6706181008 - Fachrul Faathirullah - HADIR

**Comment by irgiahmadm** [comment]
6706180041 - Irgi Ahmad Maulana - Hadir

**Comment by dewaadityaarmanda** [comment]
6706184004 -Dewa Aditya Armanda-HADIR

**Comment by alfathabibi** [comment]
6706183049 - Muhammad Alfath Abibi - HADIR

**Comment by dickymujantara** [comment]
6706181088 - Muhammad Dicky Mujantara - HADIR

**Comment by RendiWinurdani** [comment]
6706184084 - Rendi Winurdani - HADIR

**Comment by AnderaFamuzia** [comment]
6706184034-Muhamad Andera Famuzia-HADIR

**Comment by naufal7567** [comment]
6706181022 - Muhammad Naufal Rabbani - HADIR

**Comment by muhamadanasmustopa** [comment]
6706184026 - Muhamad Anas Mustopa - HADIR

**Comment by fhmsyhd** [comment]
6706184097 - Fahmi Imam Syuhada - HADIR

**Comment by haikalgakbar** [comment]
6706181059 - Haikal Gibran Akbar- HADIR
