### ISSUE TITLE
Pra-Asesmen #2

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#26]
Assalamu'alaikum.. Praktikum 11 modul telah selesai. Sekarang waktunya kita membahas tentang asesmen 2. Sehubungan dengan kondisi saat ini, tim dosen Mobpro telah berdiskusi, dan memutuskan untuk mengganti model asesmen 2 dari CoTS menjadi final project. Adapun ketentuan dari final project bisa dibaca di [sini](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).

Yang dilakukan sekarang: menuliskan nama aplikasi final project dan deskripsi singkatnya. Perhatikan final project temanmu, dan JANGAN buat final project yang sama. Format penulisan:
```
NIM, Nama Mahasiswa. Nama Aplikasi. Deskripsi singkat.
```

Deadline nama aplikasi final project dan deskripsi singkatnya: **21 April, jam 08:30**.

**Comment by nathanfitz** [comment]
selamat siang pak, maaf mau bertanya untuk pendaftaran nama aplikasi dan deskripsi singkatnya apakah dilakukan disini atau ada link khusus dari bapak dan kaka asprak kah pak? maaf mengganggu waktunya pak

**Comment by indraazimi** [comment]
@nathanfitz, tulis di sini. Biar yang lain bisa baca juga. Jadi nggak buat project yang sama.. Tulisnya sesuai format ya!

**Comment by nathanfitz** [comment]
Siap pak terimakasih pak indra

**Comment by syamfdl** [comment]
6706170086, Muhammad Hisyam Fadhil. Corona Tracker. Menampilkan data rekap kasus corona di indonesia, dan melihat kasus corono di negara lain.

**Comment by PutraBudiansyah** [comment]
6706184090, Putra Budiansyah. MyEventList. Membuat list acara dengan mencatat judul acara, deskripsi acara dan tanggal acara.

**Comment by nathanfitz** [comment]
6706174056, Nathanael Fitzgerald. List Harga Mobil. Membuat aplikasi list harga mobil beserta penjelasan singkat mobil yang tertera

**Comment by esaputramd** [comment]
6706170065, Esa Putra Mochamad Dally. Dota 2 heroes list. Menampilkan list hero hero dota 2, beserta attribut attributnya.

**Comment by biglebomb** [comment]
6706154090, Irfan Muhammad Abyan. Simple itenerary. Aplikasi perekam perjalanan liburan.

**Comment by anangmaulanap** [comment]
6706170093,Anang Maulana Prakarsa.jadwal solat.membuat aplikasi yang mengetahui jadwal solat berbagai wilayah.

**Comment by RizkyCahyana** [comment]
6706170093, Rizky Nur Cahyana .Daftar Menu Makanan Warteg . Aplikasi yang berisi daftar menu makanan warteg.

**Comment by RizkyCahyana** [comment]
6706174069, Rizky Nur Cahyana .Daftar Menu Makanan Warteg . Aplikasi yang berisi daftar menu makanan warteg dengan harga makanan dan jumlah total pembelian.

**Comment by FluxNux** [comment]
6706174035, Hizkia Tupa Christianto Sihombing. List alat musik. Aplikasi yang berisi jenis-jenis alat musik perkusi dan petik

**Comment by panjireza** [comment]
6706174109, Muhammad Panji Reza Pahlevi, Earthquake Monitoring . Aplikasi yang menampilkan data terbaru terkait gempa bumi yang terjadi.

**Comment by Amienjafar** [comment]
6706170127, Amien Jafar Makrufi, EPL. Aplikasi yang menampilkan team-team di EPL (liga inggris).

**Comment by Bayu6706174104** [comment]
6706174104, Bayu Aji Prakoso, Mini Notes. Aplikasi yang digunakan untuk mencatat kegiatan  sehari-hari yang bertujuan sebagai pengingat.

**Comment by bahrulbangsawan** [comment]
6706174118, Bahrul Bangsawan. Pengunci Layar. Aplikasi yang digunakan untuk mengunci layar hp.

**Comment by MulyaKoding** [comment]
6706174034 , Rahmat Mulya Simanjuntak. BukuHarianku . Sebuah aplikasi yang dipakai untuk menuliskan peristiwa berdasarkan waktu , pengalaman , impian ke masa depan dengan catatan tentang hidup seseorang dan bisa membuat motivasi baru untuk setiap harinya

**Comment by Ren-bit** [comment]
6706170094 - Renaldi Maulana Yusuf. SundaFood. Aplikasi yang menampilkan beragam jenis makanan khas bandung di sertai detail bumbu dan cara membuat makanan tersebut

**Comment by andrisilalahi** [comment]
6706174042, Andri Silalahi. Renungan Kristen. Aplikasi yang digunakan untuk membaca renungan di dalam isi Alkitab.

**Comment by andrisilalahi** [comment]
6706174042, Andri Silalahi. Renungan Kristen. Aplikasi yang digunakan untuk membaca renungan di dalam isi Alkitab.

**Comment by mhabli** [comment]
6706174129 - Muhammad Habli. KalkulatorYuk. Aplikasi yg digunakan untuk menghitung berbagai angka dengan adanya fitur penjumlahan, pengurangan, perkalian dan pembagian

**Comment by alifhamzah15** [comment]
6706174036 - M. Alif Muharram Hamzah. Quranku. Aplikasi untuk membaca Al - Qur'an

**Comment by andreas6674** [comment]
6706174081-Andreas Pakpahan-aplikasi organisasi-aplikasi yg berisi info tentang organisasi

**Comment by shobalubis19** [comment]
6706174055-Shoba Lubis Shokhikhi-Aplikasi Film-Aplikasi simpel menampilkan film populer

**Comment by sufiatmi** [comment]
6706170027-Sufiatmi-aplikasi wisata sulsel-aplikasi yang menampilkan nama tempat wisata dan gambar tempat wisata yang ada di sulawesi selatan

**Comment by radhitya6706174031** [comment]
6706174031 - Radhitya Kurnia W, TokView, menampilkan barang-barang toko Aksesoris yang masih tersedia beserta harga.

**Comment by dewi6706170048** [comment]
6706170048-Dewi Astriani-Aplikasi Slide Photo-Menampilkan foto foto gunung di jawa

**Comment by indraazimi** [comment]
Berhubung deadline udah terlewati, issue nya Bpk close ya! Aplikasi yang udah masuk tidak boleh diubah lagi.. Selamat mengerjakan! Semoga sukses 😄

**Comment by dheaarii** [comment]
6706160024-Dhea ari lestari- Aplikasi Karang Taruna Rukun Tetangga 006/003 Jatikramat - Aplikasi yg memudahkan warga khususnya warga lingkungan rumah RT006/003 Jatikramat Bekasi untuk mendapatkan info lingkungan, info tagihan (Kartu Dana Santunan Kematian, Sampah, Kas), lihat rekap tagihan yg telah dibayarkan dan info lainnya.
