### ISSUE TITLE
Pra-assessment 2

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#27]
Selamat Pagi.. 

Beberapa waktu yang lalu, tim dosen mobpro telah berdiskusi, dan memutuskan untuk mengganti model asesmen akhir yang awalnya coding on the spot, menjadi final project. Ketentuan dari final project bisa dibaca di [sini](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).
 
Jadi sesi praktikum online sekarang, silakan tulis nama aplikasi final project yang akan dibuat beserta deskripsi singkat aplikasi. Perhatikan final project yang telah ditulis, karena aturannya project tersebut TIDAK BOLEH SAMA antara satu dengan lainnya.

Format penulisan:
```
NIM, Nama Mahasiswa. Nama Aplikasi. Deskripsi singkat.
```

Deadline penulisan nama aplikasi final project dan deskripsi singkatnya: **22 April, jam 08:30**.

**Comment by hanifann** [comment]
6706184096, Hanifan Nurul Haq. covid-19 tracker. menampilakn jumlah pasien terinfeksi, sembuh dan meninggal.

**Comment by hanifann** [comment]
6706184096, Hanifan Nurul Haq. covid-19 tracker. Menampilkan jumlah pasien terinfeksi, sembuh dan meninggal

**Comment by resie001** [comment]
6706184007, Ade Resie Muchorobbi Setiawan. MyRepo. Menampilkan list repo pada akun github kita

**Comment by bacharuddinadieb** [comment]
6706180113, Bacharuddin Adieb Pratama, JetOPedia. Menampilkan list serta detail dari pesawat komersil.

**Comment by resie001** [comment]
6706184007, Ade Resie Muchorobbi Setiawan. MovieDB. Menampilkan list film serta detail film

**Comment by hanifann** [comment]
6706184096, Hanifan Nurul Haq. ExRates - exchange rates. Menampilkan list nilai tukar mata uang

**Comment by dodyrifkisuraya** [comment]
6706181062, Dody Rifki Suraya, News App, Menampilkan list berita serta detailnya.

**Comment by bacharuddinadieb** [comment]
6706180113, Bacharuddin Adieb Pratama. PokePedia. Menampilkan list serta detail dari Pokemon dan dapat menyimpan Pokemon favorit.

**Comment by Restuananda** [comment]
6706184087 -- Restu ananda saputra -- GoEat --Menampilkan data makanan beserta detail

**Comment by aliyyulman** [comment]
6706184070, Aliyyulman Jihan . Covid-19 tracker. Menampilkan data yang terkena covid-19.

**Comment by paulusnugroho123** [comment]
6706184033, Paulus Agata Suryonugroho.DailyTrips.Menampilkan data untuk tempat Destinasi Wisata Banyuwangi

**Comment by nwfalia** [comment]
6706180110, Nur Wakhidah Fitri Amalia. TastySpice. Menampilkan list serta detail dari rempah-rempah nusantara.

**Comment by rooflesia** [comment]
6706180044, Muhammad Rafli Naufal. SHOWROOM HELMET. Menampilkan List Helm beserta detailnya.

**Comment by abdulharis00** [comment]
6706184052, Abdul Haris. My Horoscope. menampilkan ramalan jodoh keuangan

**Comment by farhanreninda** [comment]
6706184021 - Farhan Reninda Budiansyah - MyCar - Menampilkan list Mobil

**Comment by mzakialkhairi13** [comment]
6706184117, Muhammad Zaki Alkhairi . Personalita . Aplikasi pemberi informasi seputar kepribadian

**Comment by fawwazammar** [comment]
6706181079, M. Fathin Fawwaz Ammar. Siaga. Menampilkan data gempa di Indonesia terbaru

**Comment by zhafirazahra** [comment]
6706184106, Zhafira Zahra. Vince. Menampilkan provinsi di Indonesia.

**Comment by arindameika** [comment]
6706181039, Arinda Meika Putri. Asmaul Husna. Menampilkan list data 99 Asmaul Husna beserta artinya

**Comment by yudhaprimadiansyah** [comment]
6706180083, Yudha Primadiansyah. Listronux. Menampilkan list distro linux populer saat ini

**Comment by melaniaindahsafitri** [comment]
6706184009, Melania Indah Safitri. MyFruity. Aplikasi pengenalan nama dan warna buah-buahan untuk anak TK.

**Comment by hasbifm** [comment]
6706184091, Muhammad Faishal Hasbi. IdealGram, Aplikasi yang memandu untuk mendapatkan berat badan yang ideal

**Comment by nisafitrianti** [comment]
6706184094, Nisa Fitrianti. Flower app, menampilkan list bunga dan detail bunga

**Comment by Sivanurs** [comment]
6706184014. Siva Nur Samrotissa’adah. RandomQuotes. Menggenerate quotes keren secara acak.

**Comment by yolandapurba148** [comment]
6706184135,Yolanda Stefani Putri Br Purba,StockKu. Menampilkan daftar barang yang ada di gudang

**Comment by padhisayusuf** [comment]
6706184066, Padhisa Yusuf Athif Maraya. Kumpulan Hadist,  Menampilkan berbagai hadist shahih Rasulullah Saw.

**Comment by fadhilmuqsith** [comment]
6706184048, Muh Fadhil Muqsith , Aplikasi Keuangan Pribadi , Menampilkan daftar pengeluaran keuangan.

**Comment by wahyunurrosyid** [comment]
6706180040, Wahyu Nurrosyid, Aplikasi DzikirKu, Menampilkan jenis-jenis Dzikir dalam islam dan pengertian detail serta pengamalannya

**Comment by viraashara** [comment]
6706180102, Vira Ayu Indita Ashara, Bored Things To Do, Menampilkan ide kegiatan yang dapat dilakukan ketika bosan secara acak

**Comment by lukmannurwahidin02** [comment]
6706184125,Lukman Nurwahidin, Aplikasi Pengingat,Menampilkan sebuah pengingat seperti stiky note apa yang harus di lakukan untuk kedepannya atau deadline

**Comment by utong30** [comment]
6706184058, Tamu Umbu Hunga Wohangara, Ngop's, memuat daftar menu dari coffee shop

**Comment by rbudiawan** [comment]
Okeh.. udah selesai waktu untuk input projectnya. Saya tutup sesi ini. Silahkan mengerjakan final project-nya. Semoga diberi kemudahan, dan sehat selalu.

**Comment by aliyyulman** [comment]
> 6706184070, Aliyyulman Jihan . Covid-19 tracker. Menampilkan data yang terkena covid-19.

pak punya saya ternyata udah diambil duluan sma  kelas gab. itu gimana pak?

**Comment by neyhuansikoko** [comment]
Maaf saya telat pak. Saya ketiduran. 6706180136 Neyhuan Kevin Diva Augusta Sikoko. Sleep Fact. Menampilkan fakta - fakta menarik tentang tidur secara acak.

**Comment by indraazimi** [comment]
> pak punya saya ternyata udah diambil duluan sma kelas gab. itu gimana pak?

@aliyyulman1999: Tema boleh sama. Yang nggak boleh sama itu project-nya.. Contoh: kita semua tahu WhatsApp, Telegram dan Line itu semuanya untuk chatting. Tapi tampilannya beda2 kan? Fiturnya beda, cara pakainya beda. Masing2 aplikasi tadi punya karakteristiknya masing2.

Semoga bisa dipahami 😄

**Comment by Qibro** [comment]
Maaf saya telat pak, 6706180121 Light Novel App, menampilkan list light novel, detail, dan preview dari novel tersebut.
