### ISSUE TITLE
Pra assessment 2

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#28]
Pagi.. 

Beberapa waktu yang lalu, tim dosen mobpro telah berdiskusi, dan memutuskan untuk mengganti model asesmen akhir yang awalnya coding on the spot, menjadi final project. Ketentuan dari final project bisa dibaca di [sini](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).
 
Pada sesi praktikum online kali ini, silakan tulis nama aplikasi final project yang akan dibuat beserta deskripsi singkat aplikasi. Perhatikan final project yang telah ditulis, karena aturannya project tersebut TIDAK BOLEH SAMA antara satu dengan lainnya.

Format penulisan:
```
NIM, Nama Mahasiswa. Nama Aplikasi. Deskripsi singkat.
```

Deadline penulisan nama aplikasi final project dan deskripsi singkatnya: **23 April, jam 07:30**.

**Comment by azmirizkifar20** [comment]
6706184055, Muhamad Azmi Rizkifar. Lawan Covid-19. Menampilkan informasi perkiraan jumlah pasien yang terjangkit covid-19, sembuh, dan meninggal berdasarkan provinsi juga total akumulasi pasien di semua provinsi. Dan juga menampilkan data global yang terjangkit di semua negara serta membantu user agar lebih produktif selama masa WFH.

**Comment by azmirizkifar20** [comment]
Selamat pagi pak @indraazimi @rbudiawan , maaf sebelumnya mau bertanya. Itu ketentuan project tidak boleh sama maksudnya per kelas tidak boleh sama atau tiap mahasiswa di semua kelas tidak boleh sama?
Soalnya tiap kelas kan punya jadwal yang berbeda2, jadi mungkin kelas yang jadwalnya terakhir mengalami kesulitan mengambil tema projectnya karena mungkin sudah di ambil oleh kelas lain dan kalau misalkan saya ambil tema project tentang covid-19 dan kebetulan di kelas lain juga mungkin menggunakan API yang sama dengan saya bagaimana?

Terimakasih pak

**Comment by fikri0511** [comment]
6706181071 , Muhammad Fikri Fadilah, Idealku , Membuat monitoring perubahan berat badan per-Minggunya dengan tips olahraga yang diperlukan untuk mencapai berat badan ideal

**Comment by winadarma** [comment]
6706184107, Wina Darma Rahmah. Writer PDF. Aplikasi ini adalah aplikasi yang membuat teks biasa bisa langsung menjadi PDF, dan otomatis langsung tersimpan dengan format PDF

**Comment by rbudiawan** [comment]
> Selamat pagi pak @indraazimi @rbudiawan , maaf sebelumnya mau bertanya. Itu ketentuan project tidak boleh sama maksudnya per kelas tidak boleh sama atau tiap mahasiswa di semua kelas tidak boleh sama?

@azmirizkifar20 
Project-nya unik untuk seangkatan. Kita, terutama Pak @indraazimi sebagai koordinator mata kuliah, yakin mahasiswa mobpro dasar kreatif dengan ide-idenya yang segar dan inovatif :+1: 

Mengutip pernyataan beliau, Ini sarana latihan aja.. Klo di dunia kerja, produk nggak boleh samanya se-Indonesia. Bukan cuma seangkatan. 

Jadi, silahkan disesuaikan.

**Comment by Sayyid01** [comment]
6706181063, Naufal Sayyid Furqoon. Warung Bunda, aplikasi ini akan membuat invoice dari transaksi yang ada, ditujukan untuk membantu pembukuan warung kecil, invoice akan berbentuk Struk yang bisa di ss untuk disimpan.

**Comment by azmirizkifar20** [comment]
Ouhh oke pak @rbudiawan , brarti saya harus ganti tema projectnya ya pak karena sudah diambil duluan.
Terimakasih pak

**Comment by titanhafizh** [comment]
6706184030, Titan Hafizh Surya Kusuma. Pencarian Pusat Pelayanan kesehatan. Aplikasi ini di peruntukan untuk menunjukan Pelayanan Kesehatan yang terdekat dengan pengguna

**Comment by indraazimi** [comment]
> brarti saya harus ganti tema projectnya ya pak karena sudah diambil duluan.

@azmirizkifar20: Tema boleh sama. Yang nggak boleh sama itu project-nya.. Contoh: kita semua tahu WhatsApp, Telegram dan Line itu semuanya untuk chatting. Tapi tampilannya beda2 kan? Fiturnya beda, cara pakainya beda. Masing2 aplikasi tadi punya karakteristiknya masing2.

Coba dibaca lagi penjelasan Pak @rbudiawan di atas. Pelan-pelan.. Semoga bisa dipahami 😄

**Comment by azmirizkifar20** [comment]
owalahh Alhamdulillah.. terimakasih pak informasinya @rbudiawan @indraazimi

**Comment by alfathabibi** [comment]
6706183049, Muhammad Alfath Abibi. Qashir, Aplikasi yang membantu pencatatan tiap transaksi di mini market, Barang dipindai dengan cara scan barcode setelah itu transaksi akan disimpan di dalam database

**Comment by transylvanioalfza** [comment]
6706184118. M Transylvanio Alfarezha. ToDo List. adalah aplikasi daftar tugas dan pengingat yang akan membantu pengguna dalam mencatat tugas atau kegiatan yang akan dilakukannya

**Comment by banyunurwishal** [comment]
6706184075, Banyu Nurwishal Luthfiansyam. Elements. adalah aplikasi yang menampilkan prediksi cuaca dan memberikan saran kepada pengguna sesuai cuaca yang sedang terjadi.

**Comment by FadilIlhamm** [comment]
6706184018.Fadil Ilham Muharram. ConvertYouNeeds.adalah aplikasi pengkonversi sederhana.yang berisi konversi mata uang,konversi unit seperti jarak,suhu,massa dan volume.

**Comment by Azizalfauzi** [comment]
6706180067, Aziz Alfauzi .Z-Inventory.Adalah aplikasi inventaris barang sederhana yang bertujuan untuk memudahkan user dalam pengelolaan barang yang ada di perkantoran.

**Comment by titanhafizh** [comment]
6706184030, Titan Hafizh Surya Kusuma, ManKhas, adalah aplikasi yang menampilkan list daftar Makanan Khas yang ada di indonesia.

**Comment by muhamadanasmustopa** [comment]
6706184026, Muhamad Anas Mustopa, Moozic adalah aplikasi yang menampilkan daftar music yang sedang populer di dunia saat ini

**Comment by dickymujantara** [comment]
6706181088, Muhammad Dicky Mujantara, Task n Note adalah aplikasi untuk mencatat note, planning dan daily task

**Comment by Nurilfebris** [comment]
6706180126, Nuril febri s, BukaBerita adalah aplikasi yang difungsikan untuk mendapatkan/ dapat melihat berita

**Comment by mmuhammadarief** [comment]
6706184045, Muhammad Arief Fauzan, Cloth Calculation yaitu aplikasi yang digunakan untuk menghitung pakaian yang dibeli dan menghasilkan struk pembelian untuk pembeli dan untuk pendataan penjual

**Comment by KharisZakaria** [comment]
6706180122, Kharis Zakaria, HomeDesign, aplikasi yang berisikan gambar desain rumah dan info mengenai desain tersebut

**Comment by zia123123** [comment]
6706184114,Zakatku, Aplikasi berisi tentang penghitung zakat, artikel pengertian zakat, dan tersedia juga jadwal sholat.

**Comment by miaanjani** [comment]
6706184111, Mia Anjani Darojatun Salam, MoovierevieW aplikasi yang berisi ulasan film-film atau ringkasan film-film

**Comment by dewaadityaarmanda** [comment]
6706184004, Dewa Aditya Armanda, president of indonesia Aplikasi berisi tentang biografi dari presiden pertama indonesia sampai sekarang.

**Comment by haikalgakbar** [comment]
6706181059, Haikal Gibran Akbar. BangunRuang. aplikasi yang berisi tentang macam - macam bangun ruang dan penjelasannya.

**Comment by naufal7567** [comment]
6706181022, Muhammad Naufal Rabbani, Celebes Culture, aplikasi yang menampilkan budaya dari Sulawesi

**Comment by ffaathirullah** [comment]
6706181008 Fachrul Faathirullah judul app: random cat.
deskripsi: menampilkan image kucing secara acak dan terdapat fitur favorite

**Comment by AnderaFamuzia** [comment]
6706184034 Muhamad Andera Famuzia. herbal . aplikasi ini menampilkan jenis tanaman herbal serta deskripsi manfaat dari tanaman tersebut

**Comment by rbudiawan** [comment]
Karena sudah lewat waktunya, issue ini saya close yah. Silahkan mengerjakan projectnya masing-masing sesuai ketentuan. Semoga mendapat kelancaran dan sehat selalu.

**Comment by fhmsyhd** [comment]
6706184097 Fahmi Imam Syuhada, SolveUrShape, Aplikasi yang berisi tentang rumus-rumus bangun datar dan langsung bisa menghitung soal yang kita punya

**Comment by annisanurfauziyah** [comment]
6706184099 Annisa Nur Fauziyah, My Finances
Apk ini untuk mengkontrol kuangan kita berdasarkan pemasukan dan pengeluaran. Apabila kita menambahkan uang kita maka uangnya otomasti bertambah, apabila kita melalukan pengeluaran otomatis juga akan berkurang lalu akan terdapat beberapa catatan seperti misal pengeluaran untuk apa, tanggal/waktu, jumlah pengeluaran. Lalu sebaliknya juga sperti itu untuk pemasukan.

**Comment by MaulidiyahZuhdi** [comment]
6706184011 Maulidiyah Zuhdi, Diary Avisena, aplikasi yang berisi tentang artikel atau informasi tentang jenis penyakit pada manusia

**Comment by ShakilaZahraP** [comment]
6706184103 , Shakila Zahra Previa , Coronavirus GlobalCases
Aplikasi yang berisi tentang perkiraan pasien positif , pasien meninggal , pasien sembuh , dan kasus positif skala global dalam setiap harinya dan menampilkan kasus positif corona di setiap negara.

**Comment by RendiWinurdani** [comment]
6706184084 Rendi Winurdani, Delicious , Aplikasi yang menampilkan berbagai macam menu makanan dan user dapat memesan makanan tersebut.

**Comment by haidarrp** [comment]
6706180130 Haidar Rasyid. InfoGempa. Aplikasi yang menampilkan informasi gempa yang didapatkan dari data bmkg

**Comment by sheillya** [comment]
6706184053 St Sheillya Pradina S - membuat aplikasi todo list . Aplikasi yang berisi pencatatan informasi atau goals sesorang
