### ISSUE TITLE
Pra-assessment 2

### ISSUE THREAD

**Issue by cahyana78** [D3IF-Cool/diskusi-mobpro#29]
Dear all,

Beberapa waktu yang lalu, tim dosen mobpro telah berdiskusi, dan memutuskan untuk mengganti model asesmen akhir yang awalnya **coding on the spot**, menjadi **final project**. Ketentuan dari final project bisa dibaca [di sini](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).

Jadi pada  sesi praktikum online sekarang, silakan tulis nama aplikasi final project yang akan dibuat beserta deskripsi singkat aplikasi. Perhatikan final project yang telah ditulis, karena aturannya project tersebut TIDAK BOLEH SAMA antara satu dengan lainnya.

Format penulisan:

NIM, Nama Mahasiswa. Nama Aplikasi. Deskripsi singkat.

Deadline penulisan nama aplikasi final project dan deskripsi singkatnya: **23 April, jam 07:30**.

**Comment by PutraBudiansyah** [comment]
6706184090, Putra Budiansyah. MyEventList. Membuat dan menampilkan list agenda acara dan detail acara.

**Comment by adammaulana06** [comment]
6706184057 - Adam Maulana - Aplikasi CoronaInfo. Jadi aplikasi ini menampilkan total positif orang kena corona , total sembuh orang kena corona, dan total orang meninggal kena corona.

**Comment by vironika07** [comment]
6706184105 -Vironika Ayuning Tiyas- MyAnimal. menampilkan categori dan list dari macam-macam binatang untuk anak-anak TK.

**Comment by ridhobahar1** [comment]
6706184065 - Ridho Prawira Bahari - GuitarAddictiv - menampilkan list dan deskripsi gitar, serta Chord gitar untuk pemula

**Comment by andibajangnurulizza** [comment]
6706184134 - Andi Bajang Nurul Izza - What I eat - aplikasi diary atau catatan apa saja yang dia makan dan berapa kalori yang masuk ke tubuhnya

**Comment by AndiezSatria** [comment]
6706184028 - Mohammad Andiez Satria Permana - Github User Searcher - aplikasi pencarian github user berdasarkan username dan dapat difavoritkan

**Comment by rikkylingga55** [comment]
6706180032 - Rikky Valentino Lingga - Time Table - Aplikasi untuk mengatur jadwal kegiatan sehari-hari. jadi aplikasi ini dapat menampilkan jadwal kegiataan sehari hari yang telah user atar sebelumnya.

**Comment by literally1d** [comment]
6706180024. Wandi Yusuf Kurniawan. CashierFromHome. Sebuah aplikasi berupa simulasi kasir yang melayani transaksi pembelian barang pokok selama pandemi COVID-19 serta menampilkan riwayat transaksi yang sudah dilakukan.

**Comment by rikkylingga55** [comment]
6706180032 - Rikky Valentino Lingga - Sinopsis Buku - aplikasi ini akan menampilkan berbagai macam buku dan menampilkan judul,  pengarang, tahun terbit, penerbit, estimasi harga buku, jumlah halam buku, jenis buku, dan sinopsis buku tersebut. jadi aplikasi ini akan memudahkan user untuk memilih buku yang mereka inginkan.

**Comment by shalsaazzahra11** [comment]
6706184038 - Putri Shalsabilla Azzahra - The Mountain - Aplikasi ini menampilkan list-list gunung indonesia beserta gambar dan detail nya

**Comment by MuhammadArifin22** [comment]
6706184128 - Muhammad Arifin - Aplikasi  Kisah 25 Nabi

**Comment by ahmadaamin12** [comment]
6706184078 - Ahmad Amin - Insamp - Aplikasi ini menampilkan jenis-jenis sampah beserta informasinya dan contoh hasil sampah yang di daur ulang.

**Comment by fhmbyn** [comment]
6706184095 - FAHMI AJI BAYYAN DHIYA - StyleListMan - Aplikasi ini akan menampilkan berbagai model macam rambut untuk pria yang sedang trend untuk saat ini

**Comment by alifiaulilalbab** [comment]
6706184077-Alifia Ulil Albab-Ramalan Cuaca-Aplikasi ini akan menampilkan ramalam cuaca di indonesia.

**Comment by farhanshofwani1159** [comment]
6706184047 - Farhan Shofwani - Food Recipes - aplikasi ini akan menampilkan list resep makanan dan juga bisa menulis resep makanan.

**Comment by deltaputrii** [comment]
6706184109 - Delta Putri Dewanda - PantunKu - Aplikasi ini menampilkan beberapa list pantun dan jenis jenis pantun.

**Comment by hafidsuhanizar09** [comment]
6706183043 - Hafid Suhanizar - Info Film - Aplikasi ini menampilkan informasi - informasi film , trailer film , pemeran , ranting film  dll.

**Comment by syahudanahatmasuni** [comment]
6706181120, HNW Syahuda N. Autism Therapy Payment App. Aplikasi yang didalamnya berguna untuk mencatat data transaksi pelanggan terapi autis.

**Comment by nurhidayahputeri** [comment]
6706184101 - Nurhidayah Puteri - TradFood- Aplikasi menampilkan makanan khas dari seluruh daerah di Indonesia beserta dengan deskripsi tiap makanannya.

**Comment by ikhbalrz** [comment]
6706180124 - Muhammad Ikhbal Rezanika - Ragam Budaya - Aplikasi ini akan menampilkan Ragam Budaya yang ada di Indonesia

**Comment by Farhancaandra** [comment]
6706184132-Farhan Candra Nugraha -Lampung Kyai- aplikasi yang menampilkan segala sesuatu tentang Lampung

**Comment by ahmadridhoiwananda** [comment]
6706184020 - Ahmad Ridho Iwananda - Catatan Dhuafa - Aplikasi ini dirancang untuk pribadi siapapun yang ingin mewakili/menyampaikan aspirasi kaum dhuafa

**Comment by BagusTetuko** [comment]
6706180086 - Bagus Tetuko - Fishnia - Aplikasi yang menampilkan List ikan hias air tawar beserta informasi dan tata cara perawatanya.

**Comment by TLredmagic** [comment]
6706184061 - Dany Razzaq Farino - AltSpeak - App pembicara, memanfaatkan text to speech android dan menambahkan user configurable voice.

**Comment by muhamadadjis2** [comment]
6706180073 - M Pinki Adjis - FriendEmailList - app untuk menyimpan email dari teman teman dan dapat menyimpan foto dari pemilik email yg di simpan
