### ISSUE TITLE
Praktikum modul 9: Connect to the Internet

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#3]
Assalamu'alaikum.. Praktikum kali ini kita akan coba melakukan **sesi interaktif minim kuota** melalui diskusi via issue Github. Bagi yang sudah siap praktikum di komputer/laptopnya masing-masing, harap absen terlebih dahulu.

Format:
NIM - Nama - HADIR. Pertanyaan terkait materi (jika ada)

Contoh:
6706170000 - Indra Azimi - HADIR. Tidak ada pertanyaan, karena penjelasan Udacity sudah cukup.

**Comment by syamfdl** [comment]
6706170086 - Muhammad Hisyam Fadhil - HADIR. Tidak ada pertanyaan, karena penjelasan di Codelabs sudah cukup.

**Comment by Bayu6706174104** [comment]
6706174104 - Bayu Aji Prakoso - HADIR. Tidak ada pertanyaan, karena penjelasan Codelabs sudah cukup.

**Comment by anangmaulanap** [comment]
6706170093-Anang maulana prakarsa-HADIR.Tidak ada pertanyaan,karna penjelasan Codelabs sudah cukup.

**Comment by esaputramd** [comment]
6706170065 - esa putra - HADIR, belum adanya pertanyaan, karena materi yang dipelajari belum terpelajari semuanya

**Comment by Ren-bit** [comment]
6706170094 - Renaldi Maulana Yusuf - HADIR. Belum ada pertanyaan, karena penjelasan di Codelabs sudah cukup.

**Comment by dewi6706170048** [comment]
6706170048 - Dewi Astriani - HADIR. Tidak ada pertanyaan, karena penjelasan Codelabs sudah cukup.

**Comment by MulyaKoding** [comment]
6706174034- Rahmat Mulya Simanjuntak - HADIR- Belum ada pertanyaan. karena melalui codelab yang dijelaskan dan melalui vidio di udacity sudah cukup

**Comment by nathanfitz** [comment]
6706174056-Nathanael Fitzgerald-HADIR. Belum ada pertanyaan, karena penjelasan codelabs dirasa sudah cukup

**Comment by mhabli** [comment]
6706174129 - Muhammad Habli - Hadir, belum ada pertanyaan, karena penjelasan di codelabs sudah cukup

**Comment by biglebomb** [comment]
6706154090 - Irfan Muhammad Abyan- HADIR. Belum ada.

**Comment by Amienjafar** [comment]
6706170127- Amien Jafar Makrufi - HADIR. Tidak ada pertanyaan, karena penjelasan di Udacity sudah cukup.

**Comment by radhitya6706174031** [comment]
6706174031 - Radhitya Kurnia Wijaya - Hadir - Belum ada pertanyaan, dari codelabs dan udacity sudah cukup.

**Comment by andrisilalahi** [comment]
6706174042 - Andri Silalahi - HADIR.Belum ada pertanyaan,karena penjelasan dari codelabs sudah cukup.

**Comment by sufiatmi** [comment]
6706170027-Sufiatmi- HADIR. Tidak ada pertanyaan, karena penjelasan dari udacity sudah cukup

**Comment by shobalubis19** [comment]
6706174055 - Shoba Lubis Shokhikhi - HADIR. Tidak ada pertanyaan, karena penjelasan di Udacity sudah cukup. Tapi saya Selalu kesulitan mengerjakan jurnal karena gradle saya lama pak.

**Comment by FluxNux** [comment]
6706174035- Hizkia Tupa Christianto Sihombing - HADIR. Tidak ada pertanyaan, karena penjelasan dari Udacity dan Codelabs bisa saya pahami pak.

**Comment by indraazimi** [comment]
@shobalubis19 komputer/laptop-mu prosesornya apa? RAM berapa?

**Comment by dheaarii** [comment]
6706160024 - Dhea Ari Lestari - HADIR. Tidak ada pertanyaan, karena penjelasan pada codelabs cukup jelas.

**Comment by shobalubis19** [comment]
Prosesor saya Core i3 Ram 4 pak @indraazimi

**Comment by bahrulbangsawan** [comment]
6706174118 - Bahrul Bangsawan - HADIR. Tidak ada pertanyaan.

**Comment by alifhamzah15** [comment]
6706174036 - M. Alif Muharram Hamzah - HADIR. Tidak ada pertanyaan pak, karena penjelasan dari udacity sudah cukup dak bisa saya pahami pak.

**Comment by panjireza** [comment]
6706174109 - Muhammad Panji Reza - HADIR. Tidak ada pertanyaan, karena penjelasan di Codelabs sudah cukup.

**Comment by indraazimi** [comment]
@shobalubis19 bisa ikuti tutorial ini biar Android Studio dan Gradle bisa bisa lebih kencang: https://android.jlelse.eu/is-your-android-studio-always-slow-heres-how-to-speed-up-immediately-326ef9238024

Btw, buat semua, berhubung jam sesi teorinya dah habis, klo masih ada pertanyaan, silahkan lanjut ke asprak ya! Asprak insya Allah standby di sini sampai jam 12:30.

**Comment by RizkyCahyana** [comment]
6706174069 - Rizky Nur Cahyana - HADIR. Tidak ada pertanyaan, karena penjelasan di Udacity sudah cukup bisa dipahami.

**Comment by andreas6674** [comment]
6706174081 - ANDREAS PAKPAHAN - HADIR

**Comment by andreas6674** [comment]
6706174081 - Andreas pakpahan - Hadir. Tidak ada pertanyaan, karena penjelasan di Codelabs sudah cukup.
