### ISSUE TITLE
Pra-Asesmen #2

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#30]
Assalamu'alaikum.. Praktikum 11 modul telah selesai. Sekarang waktunya kita membahas tentang asesmen 2. Sehubungan dengan kondisi saat ini, tim dosen Mobpro telah berdiskusi, dan memutuskan untuk mengganti model asesmen 2 dari CoTS menjadi final project. Adapun ketentuan dari final project bisa dibaca di [sini](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).

Yang dilakukan di sini sekarang: menuliskan nama aplikasi final project dan deskripsi singkatnya. Perhatikan final project temanmu, dan JANGAN buat final project yang sama. Format penulisan:
```
NIM, Nama Mahasiswa. Nama Aplikasi. Deskripsi singkat.
```

Deadline nama aplikasi final project dan deskripsi singkatnya: **23 April, jam 12:30**.

**Comment by bayusalam** [comment]
6706184046, Muh Yunus Bayusalam. MyGFList. Aplikasi mencatat tanggal jadian bersama nama pacar user

**Comment by cutsyarifaa** [comment]
6706184012, Cut Syarifa Alia. ExploreBdg. merupakan aplikasi yang menampilkan list rekomendasi restoran dan tempat wisata yang ada di bandung

**Comment by dinditaufa** [comment]
6706184131, Aufa Aninditya Ramadhan. Timer App. Aplikasi pengatur waktu

**Comment by adniasalsabila** [comment]
6706184133, Adnia Salsabila Ilham. Self Quarantine. aplikasi pencatat track keadaan karantina seseorang selama 14 hari dan dilengkapi info terkait covid19

**Comment by wandaalifia** [comment]
6706180054, Wanda Alifia. Habit Tracker. Aplikasi pencatat kebiasaan yang telah dilakukan

**Comment by fresyams** [comment]
6706184104, Fresya Maharani Sentosa. Moview. merupakan review dan rekomend film terbaru, baik film dalam negeri maupunfilm luar negeri

**Comment by fattahazzam** [comment]
6706184036 Azzam Fattahulhaq Santoso. Sensus Penduduk Jatisari. Aplikasi yang dapat menambah dan melihat data dari warga Jatisari

**Comment by sekarns** [comment]
6706184035, Sekar Nawang Sukma. Scheduler. aplikasi pencatat jadwal

**Comment by rdfariz** [comment]
6706184127, Raden Fariz Insan P. Short Links. Aplikasi yang berguna untuk mengkonversi url menjadi lebih pendek, beserta fitur tracking url.

**Comment by SaidSamaludin** [comment]
6706184042, Said Samaludin. family data. aplikasi yang berguna untuk mencatat data saudara kandung

**Comment by aristrisnawan** [comment]
6706184056 Aris Trisnawan. Scoring. Aplikasi untuk pencatatan score pertandingan bola basket dan dapat melihat hasil pertandingan sebelumnya

**Comment by indraazimi** [comment]
> MyGFList. Aplikasi mencatat tanggal jadian bersama nama pacar user

@bayusalam: project-nya ini harus **DIGANTI** ya! Kan di kelas udah pernah kita bahas..

**Comment by bagusizzanm** [comment]
6706180060, Muhammad Bagus Izzan Muafy. DoneGames. Aplikasi pencatatan daftar game yang sudah dimainkan.

**Comment by weslysiallagan04** [comment]
6706181081, Wesly Siallagan. Pangkas (Pencatat Uang Kas). Aplikasi pencatatan uang kas dari suatu kelompok, user dapat menambahkan data kas yang masuk serta merubahnya atau menghapusnya.

**Comment by rynzler07** [comment]
6706184119, Fauzian Pradana Putra. CashQoo. Aplikasi pencatat pemasukan/pengeluaran keuangan.

**Comment by isubhakti** [comment]
6706181023, Muhammad Imam Subhakti. WishList . Aplikasi pencatat daftar barang yang ingin dibeli

**Comment by irfanmaulanasidiq** [comment]
6706184010, IRFAN MAULANA SIDIQ. tour.aplikasi tentang rekomendasi tempat wisata

**Comment by bayusalam** [comment]
6706184046, Muh Yunus Bayusalam. PetNote. Aplikasi pencatatan data diri peliharaan

**Comment by Arzuto** [comment]
6706184098, Muhammad Arya Dhafa Rodial Widi. WasHere. Aplikasi pencatatan lokasi yang pernah user kunjungi

**Comment by SyahrulRamadhani21** [comment]
6706184068-Syahrul Ramadhani .Dinoque. Aplikasi yang berisi data-data dinosaurus

**Comment by dinditaufa** [comment]
6706184131, Aufa Aninditya Ramadhan. ToDoList. Aplikasi pencatat hal yang akan dikerjakan user pada waktu tertentu

**Comment by suryatrisna** [comment]
6706180027 - Surya Trisna Pratama . StoryNotes . Applikasi tentang penulisan cerita pribadi dalam diri kita sendiri

**Comment by didiarish** [comment]
6706184089 - I Komang Arishaldy P V . Fitness . Aplikasi pengecekan kebugaran

**Comment by alfathgandhi** [comment]
6706180093 - Alfath Gandhi I. UFO (USD Info) . Aplikasi Kurs US Dollar terupdate

**Comment by Dzaksp93** [comment]
6706184115 - Dzaki Ahmad F.A . CarsList. Aplikasi info tentang jenis - jenis mobil yang ada di Indonesia.

**Comment by BasariResha** [comment]
6706181050 - Basari Resha . ATA (After The Activity) . Aplikasi pencatat kegitan yg telah dilakukan.

**Comment by irfanmaulanasidiq** [comment]
6706184010, IRFAN MAULANA SIDIQ. DiaryNote Aplikasi yang di gunakan untuk menulis sesuatu yang kita inginkan

**Comment by irfanmaulanasidiq** [comment]
6706184010, IRFAN MAULANA SIDIQ. LISWisata Aplikasi yang di gunakan untuk mencatat wisata di daerah bogor

**Comment by arifmukh** [comment]
6706162095 - ARIF MUKHNA ARAFAH - REMINDme, adalah aplikasi android untuk mengingatkan user berdasarkan waktu yang di tentukan user tersebut.

**Comment by indraazimi** [comment]
Berhubung deadline udah terlewati, issue nya Bpk close ya! Aplikasi yang udah masuk tidak boleh diubah lagi.. Selamat mengerjakan! Semoga sukses 😄
