### ISSUE TITLE
Asesmen #2

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#31]
Assalamu'alaikum.. Minggu lalu kita udah menuliskan nama aplikasi final project dan deskripsi singkatnya. Hari ini silahkan tulis progress pengerjaan aplikasinya ya.. Fitur apa yang udah, dan fitur apa yang belum. Pastikan juga final project nya mengikuti [ketentuan](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md). Format:
```
NIM, Nama. Fitur yang udah. Fitur yang belum.
```
Progress final project ditunggu maksimal besok, **28 April jam 08:30**.

---
_REMINDER:
Side project dan video testimoni dikumpul maksimal hari ini, 27 April jam 12:30.
Final project dikumpul maksimal minggu depan, 4 Mei jam 12:30._

**Comment by nathanfitz** [comment]
6706174056, Nathanael Fitzgerald. MVVM dan Recycler view pada list layout dan cardview layout. SQLITE, Background Processing dan Mendukung pengguna berkebutuhan khusus

**Comment by syamfdl** [comment]
6706170086, Muhammad Hisyam Fadhil. MVVM dan get data API data rekap corona global dan Indonesia. RecyclerView perkembangan corona per provinsi di indonesia, Background Processing dan FItur untuk mendukung pengguna yang memilki kebutuhan khusu.

**Comment by anangmaulanap** [comment]
6706170093.Anangmaulana.(yang udah)baru membuat layout untuk memilih kota/daerah.(yang belum)jadwal semua waktu shalat untuk memasukan ke dalam layout kota yang di pilih.

**Comment by esaputramd** [comment]
6706170065. Esa Putra Mochamad Dally, membuat layout, recylerview, pembuatan koneksi ke web

**Comment by Bayu6706174104** [comment]
6706174104. Bayu Aji Prakoso.MVVM Dan menampilkan data Arraylist di Receycler View. Edit data, SQLITE, dan Mendukung pengguna berkebutuhan khusus.

**Comment by MulyaKoding** [comment]
6706174034, Rahmat Mulya Simanjuntak. Membuat layout aplikasi , database Edit ,Insert data dan delete , MVVM aplikasi, , Fitur Mendukung pengguna yang berkebutuhan khusus , dalam proses pembuatan post data ke server dan background processing.

**Comment by biglebomb** [comment]
6706154090, Irfan Muhammad Abyan. Fitur tambah rekor travel. Fitur tambah tempat spesifik ketika travelling beserta costnya, fitur share rekor travel ke orang lain.

**Comment by andrisilalahi** [comment]
6706174042, Andri Silalahi.Membuat layout,RecyclerView untuk menampilkan data dan memilih renungan kristen.

**Comment by FluxNux** [comment]
6706174035, Hizkia Tupa Christianto Sihombing. Membuat layout serta pilihan untuk jenis-jenis instrumen berserta namanya, RecyclerView, MVVM. Untuk fitur yang belum  Background Processing , Mendukung pengguna berkebutuhan khusus, SQLite.

**Comment by panjireza** [comment]
6706174109, Muhammad Panji Reza. Get Data API dari server, Menampilkan data menggunakan RecyclerView, Mendukung pengguna berkebutuhan khusus. Background Processing, SQLIte,  MVVM Architecture.

**Comment by bahrulbangsawan** [comment]
6706174118, Bahrul Bangsawan. Membuat layouting. Arsitektur MVVM, SQLite, Recycleview, workmanager.

**Comment by alifhamzah15** [comment]
6706174036, M. Alif Muharram Hamzah. Tampilan layout untuk Al-qur'an. Background processing, SQLite, MVVM, tampilan untuk berkebutuhan khusus

**Comment by indraazimi** [comment]
Waktu udah habis. Jadi kita close issue nya ya.. Semoga pengerjaan final project nya lancar.
