### ISSUE TITLE
Assessment #2

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#32]
Pagi.. pada issue kali ini, silahkan dituliskan progress dari aplikasi final project mata kuliah mobpro. Bisa dituliskan fitur apa yang sudah selesai dan belum selesai. Pastikan juga final project nya mengikuti [ketentuan](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md). 

Format penulisan:

 ```
 NIM, Nama. Fitur yang udah. Fitur yang belum.
 ```

Progress final project ditunggu maksimal besok, **29 April jam 08:30**.

_REMINDER: Side project dan video testimoni dikumpul maksimal hari ini, 28 April jam 12:30. Final project dikumpul maksimal minggu depan, 5 Mei jam 12:30._

**Comment by narayanaagung** [comment]
6706180025, Agung Narayana Adhi Putra.Beberapa fragment dan dataBinding sudah ditambahkan.Namun codingan seperti onclicklistener dan sisanya masih belum selesai

**Comment by yudhaprimadiansyah** [comment]
6706180083, Yudha Primadiansyah. Baru Membangun Fragment dan Mempersiapkan REST Server untuk data Online

**Comment by rooflesia** [comment]
6706180044. Muhammad Rafli Naufal. Fragment, Data. Tampilan, navigasi, dan sisanya.

**Comment by bacharuddinadieb** [comment]
6706180113. Bacharuddin Adieb Pratama. mempersiapkan REST API data, template fragment, menampilkan data region, menampilkan gambar region. menampilkan data pokemon, menampilkan gambar pokemon, favorite pokemon

**Comment by Restuananda** [comment]
6706184087 -- Restu ananda saputra -- dalam tahap pembuatan layout dan mempersiapkan API

**Comment by paulusnugroho123** [comment]
6706184033, Paulus Agata Suryonugroho, menyiapkan Rest APi, membuat layout dan pembuatan fragment

**Comment by lukmannurwahidin02** [comment]
6706184125 -- Lukman Nurwahidin -- Proses pembuatan fragment,data,template terbaru dan menganalisis kurangnya dari aplikasi baju adat nusantara apa yang harus di tambahkan, dan menyiapkan untuk API

**Comment by hanifann** [comment]
6706184096, Hanifan Nurul Haq. menampilkan nilai tukar mata uang, mengambil data dari api, menyimpan data pada SQLite. Recycler view, background proses, mendukung pengguna berkebutuhan khusus

**Comment by hasbifm** [comment]
6706184091, Muhammad Faishal Hasbi. membuat frament tampilan awal, menampilkan BMI, menyimpan data ke database

**Comment by wahyunurrosyid** [comment]
6706180040, Wahyu Nurrosyid. Menyiapkan API. Recicle view,dll

**Comment by resie001** [comment]
6706184007, Ade Resie Muchorobbi Setiawan. Room, Retrofit + OKHttp3, Moshi, Navigation + SafeArgs, . MVVM, WorkManager dan support kebutuhan khusus.

**Comment by farhanreninda** [comment]
6706184021, Farhan Reninda Budiansyah. Tahap mempersiapkan API. fragment, Recycler view, layout, dll

**Comment by dodyrifkisuraya** [comment]
6706181062, Dody Rifki Suraya. Buat view, model . ViewModel, getData API, RecycleView,Room, WorkManager.

**Comment by fawwazammar** [comment]
6706181079, M. Fathin Fawwaz Ammar. View. Tampil data, Background Processing, Mendukung berkebutuhan khusus.

**Comment by mzakialkhairi13** [comment]
6706184117,Muhammad Zaki Alkhairi . Baru Membuat Fragment , Layout  dan Mempersiapkan REST Server untuk data Online

**Comment by zhafirazahra** [comment]
6706184106, Zhafira Zahra. Mempersiapkan REST API, Fragment. RecyclerView, MVVM, Room, Menyimpan data ke server, Work Manager, Mendukung pengguna berkebutuhan khusus.

**Comment by arindameika** [comment]
6706181039, Arinda Meika Putri. Menyiapkan Rest API dan membuat view. ViewModel, Room db, Recyclerview, menampilkan data dr server, work manager, mendukung pengguna berkebutuhan khusus.

**Comment by aliyyulman** [comment]
6706184070, Aliyyulman Jihan. - . ViewModel, getData API, RecycleView,Room, WorkManager,background processing, Mendukung berkebutuhan khusus.

**Comment by Sivanurs** [comment]
6706184014, Siva Nur Samrotissa'adah. menampilkan fragment awal, getData API. menyimpan data ke database, mendukung berkebutuhan khusus

**Comment by melaniaindahsafitri** [comment]
6706184009, Melania Indah Safitri. Fragment, Menyiapkan REST API, Membuat View. MVVM, Room database, RecyclerView, Tampil data server, Work Manager, Pengguna Berkebutuhan Khusus.

**Comment by nwfalia** [comment]
6706180110. Nur Wakhidah Fitri Amalia. Menyiapkan REST API, fragment. MVVM, Room, RecyclerView, background processing, pengguna berkebutuhan khusus.

**Comment by padhisayusuf** [comment]
6706184066. Padhisa Yusuf Athif Maraya. Menyiapkan REST API, membuat fragment awal. MVVM, Room Database dll.

**Comment by fadhilmuqsith** [comment]
6706184048. Muh Fadhil Muqsith. Membuat Layout , Menyimpan Data ke database , Mendukung pengguna berkebutuhan khusus

**Comment by utong30** [comment]
6706184058, Tamu Umbu Hunga Wohangara. masih tahap awal (Layout, Navigasi, fragment). MVVM, database, pengguna kebutuhan khusus

**Comment by rbudiawan** [comment]
Okeh, progressnya udah dicatat. Semoga mendapat kelancaran & kemudahan untuk membuat project-nya hingga waktu pengumpulan nanti.

**Comment by abdulharis00** [comment]
6706184052, Abdul Haris , membuat tampilan awal home fragment

**Comment by viraashara** [comment]
6706180102, Vira Ayu Indita Ashara. Membuat fragment, menyiapkan rest API. MVVM, Room, RecyclerView, dll.

**Comment by yolandapurba148** [comment]
6706184135,Yolanda Stefani Putri Br Purba. Membuat fragment, MVVM, dan recycler view

**Comment by nisafitrianti** [comment]
6706184094, Nisa Fitrianti. membuat fragment dan recycler view

**Comment by Qibro** [comment]
6706180121, Muhammad Ibrahim. Membuat layout, mvvm, fragment
