### ISSUE TITLE
Assessment #2

### ISSUE THREAD

**Issue by cahyana78** [D3IF-Cool/diskusi-mobpro#33]
Dear all, 
Pada issue kali ini, silahkan dituliskan progress dari aplikasi final project mata kuliah Mobpro. Mangga dituliskan fitur apa yang sudah selesai dan belum selesai. Pastikan juga final project nya mengikuti [ketentuan](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md).

Format penulisan:

NIM, Nama. Fitur yang sudah. Fitur yang belum.
Progress final project ditunggu maksimal besok, **Kamis, 30 April jam 07:30.**

_REMINDER: Side project dan video testimoni dikumpul maksimal hari ini, 29 April jam 12:30. Final project dikumpul maksimal minggu depan, 5 Mei jam 12:30._

**Comment by muhamadadjis2** [comment]
6706180073 - M Pinki Adjis 
Sudah :
MVVM
Recyclerview
Database(Room)

Belum :
Background Processing
Mendukung pengguna berkebutuhan khusus

**Comment by nurhidayahputeri** [comment]
6706184101, Nurhidayah Puteri. Recyclerview, MVVM. Room, Background processing, Support pengguna berkebutuhan khusus.

**Comment by AndiezSatria** [comment]
6706184028, Mohammad Andiez Satria Permana, kurang background processing dan SQLite (Room)

**Comment by fhmbyn** [comment]
6706184095, FAHMI AJI BAYYAN DHIYA,kurang background processing dan mengambil data dari internet

**Comment by farhanshofwani1159** [comment]
6706184047, Farhan Shofwani. Sudah : MVVM, Recyclerview, Database(Room). Belum : Kebutuhan Khusus, Background Processing.

**Comment by shalsaazzahra11** [comment]
6706184038, Putri Shalsabilla Azzahra,Sudah : MVVM,Recyclerview. Belum : Database SQLite (Room),background processing, Support pengguna berkebutuhan khusus.

**Comment by vironika07** [comment]
6706184105, Vironika Ayuning Tiyas. MVVM, Recycleview dan Membuat Rest API. SQLite, Background Prossessing, Kebutuhan Khusus

**Comment by literally1d** [comment]
6706180024, Wandi Yusuf Kurniawan.
Done: MVVM, SQLite, RecyclerView.
Not yet: REST API, Background Processing, User with special needs.

**Comment by syahudanahatmasuni** [comment]
6706181120, HNW Syahuda N. Fitur yang sudah : MVVM, Recycler View, Database (room) . Fitur yang belum : Background Processing, Kebutuhan Khusus.

**Comment by deltaputrii** [comment]
6706184109, Delta Putri Dewanda. Sudah : MVVM, RecyclerView. Belum : Database SQLite(Room), Background Processing, Kebutuhan Khusus.

**Comment by ahmadridhoiwananda** [comment]
6706184020. Ahmad Ridho Iwananda. MVVM, SQLite, Recyclerview. Background Processing, Pengguna Kebutuhan Khusus.

**Comment by PutraBudiansyah** [comment]
6706184090, Putra Budiansyah.sudah : MVVM, Recycler View, Database (room) .belum : Background Processing, Kebutuhan Khusus.

**Comment by rikkylingga55** [comment]
6706180032, Rikky Valentino Lingga
  Fiture yang sudah : MVVM, Recycler View, Database . 
 Fitur yang belum : Background Processing, Kebutuhan Khusus.

**Comment by Farhancaandra** [comment]
6706184132, Farhan Candra Nugraha sudah :MVVM, Recycler View belum: Database,Background Processing, Kebutuhan Khusus.

**Comment by ahmadaamin12** [comment]
6706184078, Ahmad Amin, sudah = MVVM, Database, Recycler View belum = Background Processing, Berkebutuhan Khusus

**Comment by fachranwardi10** [comment]
6706184001
Fachran Setiawan Wardi
Sudah = MVVM, Database, Recycler View
Belum = Background Processing, Berkebutuhan Khusus

**Comment by ikhbalrz** [comment]
6706180124, Muhammad Ikhbal Rezanika
Sudah : RecyclerView, Mvvm
Belum : get data api, offline caching, mendukung pengguna berkebutuhan khusus

**Comment by alifiaulilalbab** [comment]
6706184077 
Alifia Ulil Albab
Sudah = MVVM, Recycler View
Belum = Database, background processing, Berkebutuhan khusus

**Comment by ridhobahar1** [comment]
6706184065
Ridho Prawira Bahari
sudah = MVVM , Recycler View
Belum = Database sqlite room, background processing, Berkebutuhan khusus

**Comment by adammaulana06** [comment]
6706184057, Adam Maulana yang sudah : MVVM, RecyclerView,Database . Yang belum
REST API, Background Processing, Berkebutuhan khusus

**Comment by hafidsuhanizar09** [comment]
6706183043 , Hafid Suhanizar , Yang Sudah : MVVM, RecylerView, Dan Database, Belum = Background Processing, Berkebutuhan Khusus

**Comment by BagusTetuko** [comment]
6706180086 , Bagus Tetuko , Sudah : MVVM , ReyclerView , Belum :  Database, background processing, mendukung pengguna Berkebutuhan khusus

**Comment by cahyana78** [comment]
Oke, terima kasih untuk yang sudah menuliskan progress nya. Selamat mengerjakan untuk backgroud processing dan lainnya, semoga lancar dan mendapatkan hasil yang diinginkan ya

**Comment by MuhammadArifin22** [comment]
Muhammad Arifin - 6706184128 : Sudah : ReclyeView, MVVM blm : database , background procesing dan berkebutuhan khusus
