### ISSUE TITLE
Assessment #2

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#34]
Pagi.. pada issue kali ini, silahkan dituliskan progress dari aplikasi final project mata kuliah mobpro. Bisa dituliskan fitur apa yang sudah selesai dan belum selesai. Pastikan juga final project nya mengikuti [ketentuan](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md). 

Format penulisan:

 ```
 NIM, Nama. Fitur yang udah. Fitur yang belum.
 ```

Progress final project ditunggu maksimal besok, **30 April jam 07:30**.

_REMINDER: Side project dan video testimoni dikumpul maksimal hari ini, 29 April jam 11:30. Final project dikumpul maksimal minggu depan, 6 Mei jam 11:30._

**Comment by Sayyid01** [comment]
6706181063, Naufal Sayyid Furqoon. Tambah item, Menampilkan Item yang sudah ditambahkan, Meghapus keseluruhan item yang ada di list. Belum bisa hapus per item, Belum ada bagian yang menampilkan total harga, About, Dark mode, Aksesibilitas.

**Comment by azmirizkifar20** [comment]
6706184055, Muhamad Azmi Rizkifar. Recyclerview, MVVM, offline caching (room db), API service (get data), live search, membantu user agar produktif. Background processing dan support pengguna berkebutuhan khusus.

**Comment by titanhafizh** [comment]
6706184030 , Titan Hafizh Surya Kusuma . Recyclerview, MVVM, retrofit . offline caching (room db), background processing, mendukung pengguna berkebutuhan khusus

**Comment by ffaathirullah** [comment]
6706181008 Fachrul Faathirullah , sudah selesai : get data dari firebase, set as background, crop, , download gambar, share aplikasi,Background processing dan support pengguna berkebutuhan khusus.,MVVM exit. belum selesai : menu favorite gambar menggunakan room / lainnya,

**Comment by zia123123** [comment]
6706184114, Zia Muhammad. API service,MVVM, Recyclerview . room db, mendukung pengguna berkebutuhan khusus

**Comment by Azizalfauzi** [comment]
6706180067,Aziz Alfauzi,sudah selesai : Front end sudah selesai,Recyclerview,MVVM.belum selesai : Get data dari Api server,offline-chacing(room db)

**Comment by KharisZakaria** [comment]
6706180122, Kharis Zakaria. Sudah : RecyclerView,  Mvvm.
Belum : get data api, offline caching, mendukung pengguna berkebutuhan khusus.

**Comment by fhmsyhd** [comment]
6706184097 - Fahmi Imam Syuhada

Sudah :
MVVM
Recyclerview

Belum : 
Database
Background Processing
Mendukung pengguna berkebutuhan khusus

**Comment by fikri0511** [comment]
6706181071 - Muhammad Fikri Fadilah . Sudah : RecylerView,Mvvm,penghitungan berat Ideal,penyimpanan data perhitungan,edit data,hapus data peritem, hapus semua Data,tampilan data List perinputan,Rtl Support . 
Belum : Background processing , get dataApi(tips dan trick mendapatkan berat badan ideal
),offline cahing

**Comment by winadarma** [comment]
6706184107 - Wina Darma Rahmah. Sudah halaman awal, save data,about. Belum mendukung penggunaan berkebutuhan khusus, darkmode, Api

**Comment by dickymujantara** [comment]
6706181088 - Muhammad Dicky Mujantara
Fitur yang sudah : 
- CRUD
- Clear all data
- MVVM
- Recyclerview

Fitur yang belum:
- API
- darkmode
- background processing
- Mendukung pengguna berkebutuhan khusus

**Comment by FadilIlhamm** [comment]
6706184188 - Fadil Ilham Muharram
Fitur yang sudah :

UI
Konveter unit
Fitur yang belum:

API
background processing
MVVM
Recylerview
Mendukung pengguna berkebutuhan khusus
darkmode

**Comment by muhamadanasmustopa** [comment]
6706184026 - Muhamad Anas Mustopa
Fitur yang sudah : 
MVVM
Recyclerview
Database

Belum : 
Background Processing
Mendukung pengguna berkebutuhan khusus

**Comment by Nurilfebris** [comment]
6706180126 - Nuril febri setiyawan 
Sudah : Mvvm, RecyclerView
Belum : get data dari  api, offline caching,kebutuhan khusus

**Comment by AnderaFamuzia** [comment]
6706184034-Muhamad Andera Famuzia
Sudah : Mvvm,RecyclerView
Belum : background processing, mendukung pengguna kebutuhan khusus

**Comment by ShakilaZahraP** [comment]
6706184103 - Shakila Zahra Previa
sudah : API , Background processing , Live data , Recycler view
belum : search view, data sembuh dan data kematian tiap negara , darkmode

**Comment by transylvanioalfza** [comment]
6706184118, M Transylvanio Alfarezha.  SQLite Database, RecyclerView.  Mendukung pengguna berkebutuhan khusus, Darkmode

**Comment by banyunurwishal** [comment]
6706184075 - Banyu Nurwishal Luthfiansyam
Sudah : mvvm, recycleview, API
Belum :  background processing, berkebutuhan khusus

**Comment by naufal7567** [comment]
6706181022, Muhammad Naufal Rabbani. Sudah RecycleView dan MVVM. Belum Get Data dari API, Offline Caching, dan untuk yang berkebutuhan khusus.

**Comment by haikalgakbar** [comment]
6706181059, Haikal Gibran Akbar. RecycleView. Get Data dari API, Offline caching, untuk yang berkebutuhan khusus.

**Comment by haidarrp** [comment]
6706180130 - Haidar Rasyid Ramdana Putra
Sudah: API service,MVVM, Recyclerview 
Belum. 
Belum: background processing, berkebutuhan khusus

**Comment by mmuhammadarief** [comment]
6706184045, Muhammad Arief Fauzan. Sudah UI, Perhitungan. Belum API, background processing, mvvm recylerview, supportberkebutuhan khusus, darkmode

**Comment by dewaadityaarmanda** [comment]
6706184004 - Dewa Aditya Armanda.
selesai :
RecycleView 
MVVM
Belum : 
Get Data dari API
Support berkebutuhan khusus
darkmode

**Comment by hibbanramadhan123** [comment]
6706174010, Muhammad Hibban Ramadhan. sudah RecycleView,MVVM. belum get data API, background processing, dan kebutuhan khusus

**Comment by MaulidiyahZuhdi** [comment]
6706184011, Maulidiyah Zuhdi, ui,tambah data,tampil data, hapus data,database.

**Comment by miaanjani** [comment]
6706184111, Mia Anjanui DArojatun Salam. sudah MVVM, recyclerview. belum get data API, baclground processing, darkmode, support berkebutuhan khusus

**Comment by annisanurfauziyah** [comment]
6706184099 - Annisa Nur Fauziyah.
Database
Background Processing
Mendukung pengguna berkebutuhan khusus

**Comment by RendiWinurdani** [comment]
6706184084, Rendi Winurdanii, ui,,recyclerview,database,,tambah dan tampil data

**Comment by rbudiawan** [comment]
Silahkan melanjutkan pekerjaannya dan semoga mendapat kelancaran.

**Comment by sheillya** [comment]
6706184053 - St Sheillya Pradina
UI
database
tambah data
