### ISSUE TITLE
Asesmen #2

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#35]
Assalamu'alaikum.. Minggu lalu kita udah menuliskan nama aplikasi final project dan deskripsi singkatnya. Hari ini silahkan tulis progress pengerjaan aplikasinya ya.. Fitur apa yang udah, dan fitur apa yang belum. Pastikan juga final project nya mengikuti [ketentuan](https://github.com/D3IF-Cool/diskusi-mobpro/blob/master/final-project.md). Format:
```
NIM, Nama. Fitur yang udah. Fitur yang belum.
```
Progress final project ditunggu maksimal besok, **30 April jam 12:30**.

---
REMINDER:
- Side project dan video testimoni dikumpul maksimal hari ini, 29 April jam 16:30.
- Final project dikumpul maksimal minggu depan, 6 Mei jam 12:30.

**Comment by rdfariz** [comment]
6706184127, Raden Fariz Insan P. Fitur short links (API), history. Fitur tracking url, background processing.

**Comment by dinditaufa** [comment]
6706184131, Aufa Aninditya R. Menambah data ke database. Hapus data

**Comment by aristrisnawan** [comment]
6706184056, Aris Trisnawan.  Tampilannya.  fungsi

**Comment by isubhakti** [comment]
6706181023, Muhammad Imam Subhakti. Tampilan UI. Fungsi

**Comment by bayusalam** [comment]
6706184046, Muh Yunus Bayusalam. Layout. Fungsinya

**Comment by cutsyarifaa** [comment]
6706184012. Cut Syarifa Alia. Fragment layout. Menampilkan list

**Comment by SaidSamaludin** [comment]
6706184042, Said Samaludin. Tampilan Aplikasi. Fungsi

**Comment by rynzler07** [comment]
6706184119, Fauzian Pradana Putra. Tampilan Aplikasi. Fungsi

**Comment by fresyams** [comment]
6706184104, Fresya Maharani Sentosa. Layout hanya sebagian dan database. MVVM, layout yang belum , list movie

**Comment by bagusizzanm** [comment]
6706180060, Muhammad Bagus Izzan Muafy. UI, MVVM. Background Processing, Dark Mode

**Comment by BasariResha** [comment]
6706181050, Basari Resha. UI.Fungsi

**Comment by Arzuto** [comment]
6706184098, Muhammad Arya Dhafa Rodial Widi. Tambah,Hapus. Edit

**Comment by irfanmaulanasidiq** [comment]
6706184010,IRFAN MAULANA SIDIQ.Tampilan layout.Fungsiya

**Comment by irfanmaulanasidiq** [comment]
6706184010,IRFAN MAULANA SIDIQ.Tampilan layout.Fungsiya.

**Comment by sekarns** [comment]
6706184035, Sekar Nawang Sukma. UI, tambah data

**Comment by SyahrulRamadhani21** [comment]
6706184068, Syahrul Ramadhani. UI. Get data api, offline caching, mendukung pengguna berkebutuhan khusus.

**Comment by weslysiallagan04** [comment]
6706181081, Wesly Siallagan. UI. Fungsi CRUD, Background Processing.

**Comment by suryatrisna** [comment]
6706180027, Surya Trisna Pratama, UI dan database  , fitur hapus dan MVVM

**Comment by alfathgandhi** [comment]
6706180093, Alfath gandhi. Mengambil data dari api. Background processing

**Comment by fattahazzam** [comment]
6706184036. Azzam Fattahulhaq Santoso. UI. Menambah dan menghapus data,database.

**Comment by wandaalifia** [comment]
6706180054, Wanda Alifia. UI. Fungsi

**Comment by didiarish** [comment]
6706184089, Komang Arishaldy. Menampilkan data. mendukung pengguna berkebutuhan khusus, dark mode

**Comment by didiarish** [comment]
6706184089, Komang Arishaldy. Menampilkan data. background processing, mendukung pengguna berkebutuhan khusus

**Comment by indraazimi** [comment]
Waktu udah habis. Jadi kita close issue nya ya.. Semoga pengerjaan final project nya lancar.
