### ISSUE TITLE
Cara agar data di Room database tetap up to date secara efisien ?

### ISSUE THREAD

**Issue by dodyrifkisuraya** [D3IF-Cool/diskusi-mobpro#36]
#ASK
Selamat Sore
Izin Tanya bapak/ibu dosen atau teman-teman, 

Cara agar data di Room database tetap up to date secara efisien gimana?
Saya udah bisa refreshData Room dengan cara "Delete semua data" lalu "Insert data". Ini dilakukan tiap menit(WorkManager). Nah itu efisien belum? Apa harus dilakukan pengecekan "apakah ada perubahan data" sebelum refreshData? Gimana cara ngebandingin "data di room" dengan "data di API" ? Atau gimana?

Saya ambil data dari newsapi.org

**Comment by indraazimi** [comment]
Yang @dodyrifkisuraya lakukan sekarang itu namanya strategi **polling**. Jadi aplikasi nanya ke server setiap periode waktu tertentu. Strategi ini bagus klo perubahan datanya terjadi secara periodik..

Tapi untuk berita, kan perubahan datanya tidak periodik. Jadi lebih cocok klo pake strategi **pushing**. Jadi ketika ada perubahan data (misal ada berita baru) servernya yang ngasi tau aplikasi agar melakukan refresh data.

Strategi polling vs pushing ini materi Mobpro Lanjut tahun lalu. Klo mau explor sendiri, bisa ikuti lesson 3 kursus [Advanced Android App Development](https://www.udacity.com/course/advanced-android-app-development--ud855)

**Comment by dodyrifkisuraya** [comment]
wahh makasih pak @indraazimi
