### ISSUE TITLE
Error ketika menampilkan data dari server.

### ISSUE THREAD

**Issue by literally1d** [D3IF-Cool/diskusi-mobpro#37]
Assalamu'alaikum, pak @indraazimi , pak @rbudiawan , dan bu @cahyana78. Saya izin bertanya mengenai logcat ini:
![Screenshot (147)](https://user-images.githubusercontent.com/49407384/81015666-422b0200-8e89-11ea-9ab6-beca2fc07263.png)
Jadi, aplikasi force close ketika ingin menampilkan data dari server. Kira-kira kodingan seperti apa yang harus ditambah/diubah/dihapus? Mohon penjelasannya, terima kasih...

**Comment by indraazimi** [comment]
Dia bilang `BarangViewModel` nya nggak bisa di-create. Kenapa begitu? Ya nggak tau juga. Harus lihat project nya secara utuh dulu..

**Comment by literally1d** [comment]
Apakah mungkin berasal dari sini, pak @indraazimi ?
![image](https://user-images.githubusercontent.com/49407384/81033207-e5493f00-8ebc-11ea-957a-0e76305119fc.png)
![image](https://user-images.githubusercontent.com/49407384/81033225-f2fec480-8ebc-11ea-9ced-168ad8ccaa8e.png)

**Comment by indraazimi** [comment]
Itu `BarangViewModel` nya kan punya parameter `application`. Dah dibuatkan factory nya belum? Kayak yang di [sini](https://github.com/udacity/andfun-kotlin-dev-bytes/blob/c82e2d625c82618d9bd245877190b2693e942d4d/app/src/main/java/com/example/android/devbyteviewer/viewmodels/DevByteViewModel.kt#L83).

**Comment by literally1d** [comment]
Sudah saya tambahkan, saya coba ya...
Alhamdulillah, sudah bisa...
![image](https://user-images.githubusercontent.com/49407384/81133424-cd84c000-8f7b-11ea-9828-93167284cd07.png)
Terima kasih sudah membantu, pak @indraazimi .

**Comment by indraazimi** [comment]
Gimana? Berhasil nggak? Klo dah berhasil, issue nya di-close ya.. :smile:

**Comment by literally1d** [comment]
Sudah, pak @indraazimi ... 😄
Izin close issue, ya...
