### ISSUE TITLE
Cara get resource color dan string di view model

### ISSUE THREAD

**Issue by alfathabibi** [D3IF-Cool/diskusi-mobpro#38]
punten pak, bagaimana cara mengambil resource color dan string di viewmodel?
![image](https://user-images.githubusercontent.com/60532478/93466341-4a567c00-f916-11ea-9722-45ece62f52e3.png)

**Comment by indraazimi** [comment]
Resource color dan string itu kan buat tampilan. Jadi kodenya harusnya ada di activity/fragment, bukan di viewmodel.. Coba diperhatikan lagi contoh coding yang diberikan di modul.

**Comment by alfathabibi** [comment]
Oh iya siap pak udah ketemu solusinya
