### ISSUE TITLE
App name - modul 07 Mobpro 2

### ISSUE THREAD

**Issue by ffaathirullah** [D3IF-Cool/diskusi-mobpro#39]
maaf pa mau bertanya mengenai tubes mobpro 2 modul 07 untuk app namenya di Main store listing boleh dirubah tidak pak ???? terimakaish

**Comment by indraazimi** [comment]
Nama boleh diubah asalkan aplikasinya tetap sama.

**Comment by ffaathirullah** [comment]
siap pa terimakasih
