### ISSUE TITLE
Praktikum modul 9: connect to Internet

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#4]
Di sini, akan dilakukan presensi minimal kuota. Silahkan menuliskan Nim, nama, dan juga HADIR bagi mahasiswa yang sudah standby untuk praktikum.

**Comment by yolandapurba148** [comment]
6706184135 - Yolanda Stefani Putri Br Purba - HADIR. tidak ada pertanyaan karena penjelasan dari codelabs dan udacity sudah cukup membantu

**Comment by ridloxyanuar** [comment]
6706174072 - Ridlo Yanuar - HADIR. tidak ada pertanyaan karena penjelasan dari codelabs sudah cukup membantu

**Comment by fawwazammar** [comment]
6706181079 - M. Fathin Fawwaz Ammar - HADIR

**Comment by viraashara** [comment]
6706180102 - Vira Ayu Indita Ashara - HADIR.

**Comment by mzakialkhairi13** [comment]
6706184117 - Muhammad Zaki Alkhairi HADIR. belum ada pertanyaan karena penjelasan dari codelabs dan udacity sudah cukup membantu.

**Comment by yudhaprimadiansyah** [comment]
6706180083 - Yudha Primadiansyah - HADIR

**Comment by Rizwan-4126** [comment]
6706174126 - Rizwan Ramadhan - HADIR. Belum ada pertanyaan karena penjelasan dari codelabs dan udacity sudah cukup

**Comment by rooflesia** [comment]
6706180044 - Muhammad Rafli Naufal - HADIR

**Comment by padhisayusuf** [comment]
6706184066 - Padhisa Yusuf Athif Maraya - HADIR

**Comment by paulusnugroho123** [comment]
6706184033 - Paulus Agata Suryonugroho - HADIR.

**Comment by arindameika** [comment]
6706181039 - Arinda Meika Putri - HADIR

**Comment by bacharuddinadieb** [comment]
6706180113 - Bacharuddin Adieb Pratama - HADIR. 
![64460677-5f84-41bf-8ad7-ac39ab59cd48](https://user-images.githubusercontent.com/22101214/77976284-ca683580-7326-11ea-9195-9d3996f8a337.jpeg)
Permisi pak, untuk android P kalau mau fetch data melalui http kok ada error CLEARTEXT ya pak, tapi saya coba pakai android M normal, mohon pencerahannya pak

**Comment by farhanreninda** [comment]
6706184021 - Farhan Reninda Budiansyah - HADIR

**Comment by wisnusabani** [comment]
6706174126 - Rizwan Ramadhan - HADIR. Belum ada pertanyaan karena penjelasan dari codelabs dan udacity sudah cukup

**Comment by nwfalia** [comment]
6706180110 - Nur Wakhidah Fitri Amalia - HADIR

**Comment by wisnusabani** [comment]
6706174107 - Wisnu Almi Pradya S - HADIR.

**Comment by hanifann** [comment]
6706184096 - Hanifan Nurul Haq - HADIR

**Comment by Sivanurs** [comment]
6706184014 - Siva Nur Samrotissa’adah - Hadir.

**Comment by dodyrifkisuraya** [comment]
6706181062 - Dody Rifki Suraya - Hadir

**Comment by wahyunurrosyid** [comment]
6706180040-Wahyu Nurrosyid-Hadir-Tidak ada pertanyaan pak

**Comment by indraazimi** [comment]
@bacharuddinadieb: Android P default nya tidak support koneksi HTTP. Jadi solusinya ganti url ke koneksi secure (HTTPS) atau ikuti tutorial ini klo mau tetap pakai HTTP biasa: https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

**Comment by melaniaindahsafitri** [comment]
6706184009-Melania Indah Safitri-HADIR

**Comment by zhafirazahra** [comment]
6706184106 - Zhafira Zahra - Hadir

**Comment by utong30** [comment]
6706184058 - Tamu Umbu Hunga Wohangara - Hadir

**Comment by fadhilmuqsith** [comment]
6706184048 - Muh Fadhil Muqsith _ HADIR

**Comment by abdulharis00** [comment]
6706184052- ABDUL HARIS _HADIR

**Comment by yolandapurba148** [comment]
6706184135-YOLANDA PURABA- HADIR

**Comment by bacharuddinadieb** [comment]
> @bacharuddinadieb: Android P default nya tidak support koneksi HTTP. Jadi solusinya ganti url ke koneksi secure (HTTPS) atau ikuti tutorial ini klo mau tetap pakai HTTP biasa: https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

Terimakasih pak

**Comment by Restuananda** [comment]
6706184087 - Restu ananda saputra

HADIR

**Comment by neyhuansikoko** [comment]
6706180136 - Neyhuan Kevin Diva Augusta Sikoko - HADIR

**Comment by Qibro** [comment]
6706180121-Muhammad Ibrahim - HADIR

**Comment by zakariaf05** [comment]
6706184074 - Zakaria Firdaus - HADIR
