### ISSUE TITLE
Menampilkan data dari Room ke Chart

### ISSUE THREAD

**Issue by onedeemath** [D3IF-Cool/diskusi-mobpro#40]
Assalamu'alaikum, Pak @indraazimi dan Pak @rbudiawan. Saya mencoba menggunakan library MPAndroidChart seperti di modul 2 dengan menggunakan Room, tetapi saya mengalami kendala dalam menampilkan datanya ke Chart.

Seperti ini screenshoot aplikasinya:
![device-2020-11-04-182823](https://user-images.githubusercontent.com/42926210/98106719-281bbc00-1ecc-11eb-8f65-6189e7fe8527.png)

Screenshoot kelas `HomeFragment.kt`:
![image](https://user-images.githubusercontent.com/42926210/98108239-37036e00-1ece-11eb-8ca9-8bcdcf2c97e4.png)
![image](https://user-images.githubusercontent.com/42926210/98108259-3cf94f00-1ece-11eb-9175-0b4a9de5aaf8.png)
![image](https://user-images.githubusercontent.com/42926210/98108279-4387c680-1ece-11eb-90bd-70cb28e58937.png)

Screenshoot kelas `NumbersAdapter.kt`:
![image](https://user-images.githubusercontent.com/42926210/98108366-6b772a00-1ece-11eb-90ba-acaf122d71f1.png)

Screenshoot kelas `NumbersViewModel.kt`:
![image](https://user-images.githubusercontent.com/42926210/98108502-a4170380-1ece-11eb-81db-438a7bbfc448.png)
![image](https://user-images.githubusercontent.com/42926210/98108519-aa0ce480-1ece-11eb-8316-a6cff04bcb44.png)

Jika saya mengubah kodingan di kelas `HomeFragment.kt` menjadi `viewModel.getData().observe(this.viewLifecycleOwner, {NumbersAdapter(it).setData()})`, maka logcat yang muncul akan seperti ini:
![image](https://user-images.githubusercontent.com/42926210/98109524-4daac480-1ed0-11eb-90de-5971dd30df4b.png)
padahal isi dalam databasenya sudah ada.

Kira-kira bapak bisa membantu menemukan letak kesalahan kodingan di screenshoot tersebut beserta solusinya supaya saya bisa mengoreksi kesalahan tersebut. Mohon penjelasannya dan terima kasih...

**Comment by indraazimi** [comment]
Wa'alaikum salam.. Itu pesan error nya bilang `it` bernilai null. Kenapa bisa null? Coba kita telusuri..
- `it` berasal dari `viewModel.getData()`
- `getData()` di viewModel mendapatkan nilainya dari `data`
- `data` diinisialisasi sebagai `MutableLiveData<List<Numbers>>`

Di sini `data` tidak bernilai null, namun `data.value` yang dibaca sebagai `it` di HomeFragment akan bernilai null. Karena `data.value` baru akan ada nilainya setelah method `requestData` di init viewModel selesai dijalankan.

**Solusi**: set `data.value` di awal init viewModel (baris ke-18) dengan list kosong agar tidak null.

**Comment by onedeemath** [comment]
List kosong itu berupa `emptyList()`, pak?

Edit: Tambahan screenshot kelas `NumbersDAO.kt` untuk penjelasan secara detail:
![image](https://user-images.githubusercontent.com/42926210/98389470-afad2a80-2086-11eb-99c2-1c55e18d7677.png)
Apakah saya perlu mencantumkan source code juga, pak?

**Comment by indraazimi** [comment]
> List kosong itu berupa `emptyList()`, pak?

Ya. Gimana? Bisa nggak?

**Comment by onedeemath** [comment]
Seperti ini, pak?
![image](https://user-images.githubusercontent.com/42926210/98432333-c340ab80-20ef-11eb-9977-dadeb2783d95.png)
Hasilnya masih terbaca `null` di logcat walaupun `data.value` sudah di set jadi `emptyList()`, pak.

**Comment by indraazimi** [comment]
Ya berarti method `requestData` yang menyebabkan `data.value` menjadi null. Coba dicek apakah terjadi exception di logcat?
