### ISSUE TITLE
Gagal Menambahkan viewBinding

### ISSUE THREAD

**Issue by fakhrulrz24** [D3IF-Cool/diskusi-mobpro#42]
![Screenshot (253)](https://user-images.githubusercontent.com/79067498/109407446-74c35f80-79b3-11eb-960b-6ca61a4e8e45.png)
Pak @indraazimi saya ingin bertanya, di saat saya menambahkan viewBinding pada app/build.gradle, kenapa gagal ya pak? Muncul pesan seperti ini : 

Could not find method buildFeatures() for arguments [build_drms3w22xnb9aj8b42qfpx32n$_run_closure1$_closure4@30ff13c0] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

**Comment by indraazimi** [comment]
Android Studio nya versi berapa? Sudah 4.0 ke atas?

**Comment by fakhrulrz24** [comment]
Sudah bisa pak. Sudah saya update ke versi 4.1.2

**Comment by indraazimi** [comment]
Alhamdulillah.. Issue nya Bpk close ya!
