### ISSUE TITLE
Tidak ada pilihan "Data Class"

### ISSUE THREAD

**Issue by fakhrulrz24** [D3IF-Cool/diskusi-mobpro#43]
Assalamu'alaikum, pak @indraazimi saya ingin bertanya. Di saat saya ingin menambahkan Data Class pada folder package kenapa tidak ada pilihan Data Class nya ya pak?

![Screenshot (264)](https://user-images.githubusercontent.com/79067498/110228662-5b7f5d80-7f35-11eb-8439-66ab6bdcf57b.png)

**Comment by indraazimi** [comment]
Wa'alaikum salam.. Ada dua opsi:
- Bisa update Android Studio nya ke versi terbaru biar menunya muncul.
- Atau pilih Class aja. Nanti baru codingannya disesuaikan jadi data class.

**Comment by fakhrulrz24** [comment]
Kalau Android Studio nya pak sudah saya update ke latest stable version 4.1.2. Baik pak saya akan coba opsi kedua. Terima kasih pak atas bantuannya
