### ISSUE TITLE
[Modul 3] error : Execution failed for task ':app:processDebugGoogleServices'

### ISSUE THREAD

**Issue by andibajangnurulizza** [D3IF-Cool/diskusi-mobpro#44]
![image](https://user-images.githubusercontent.com/60649492/135899456-c061a7f8-792d-4c5b-9acd-3298016f451b.png)

Assalamualaikum Pak, apabila errornya seperti ini kira-kira penyelesainnya gimana, pak? Terima kasih.

**Comment by indraazimi** [comment]
Wa'alaikum salam.. Pastikan package name yang di Firebase console sesuai dengan package name di Android Studio.

**Comment by andibajangnurulizza** [comment]
![image](https://user-images.githubusercontent.com/60649492/136811490-b149f884-6204-4c93-8c85-87535f6bd44b.png)
![image](https://user-images.githubusercontent.com/60649492/136811880-eea57962-9fa4-4449-941d-a9f195c41de5.png)
sudah sama pak, di firebase dan di projectnya

**Comment by indraazimi** [comment]
File google-services.json nya di-download ulang. Habis itu lakukan Gradle sync.
