### ISSUE TITLE
[Modul 04 - Galeri Hewan] Izin Bertanya Mengenai Repository

### ISSUE THREAD

**Issue by prabuaddin30** [D3IF-Cool/diskusi-mobpro#45]
![image_2022-03-15_163645](https://user-images.githubusercontent.com/71245237/158349194-1d2ec961-3c66-4958-86b5-c94c0ff414db.png)

Assalamualaikum pak Indra, nama saya Prabu Addin Almuhasibi, izin bertanya apakah repository nya perlu menjadi public? karena untuk sekarang repository saya dalam kondisi private

**Comment by indraazimi** [comment]
Wa'alaikum salam.. Setting default nya memang private, agar hanya kamu dan dosen yang bisa lihat. Tidak perlu dijadikan publik.

**Comment by prabuaddin30** [comment]
Oh baik pak, terima kasih atas informasinya
