### ISSUE TITLE
Praktikum modul 9: connect to Internet

### ISSUE THREAD

**Issue by rbudiawan** [D3IF-Cool/diskusi-mobpro#6]
Di sini, akan dilakukan presensi minimal kuota. Silahkan menuliskan Nim, Nama, dan juga keterangan "HADIR" bagi mahasiswa yang sudah standby untuk praktikum.

Yang punya masalah ketika mencoba materi Udacity/CodeLabs, silahkan klo mau bertanya.. Di sini kita **bukan cuman absen**, tapi untuk menyelesaikan masalah praktik yang kalian punya juga 😄

**Comment by zia123123** [comment]
Nim : 6706184114
Nama : Zia Muhammad Najieb
HADIR

**Comment by titanhafizh** [comment]
Nim : 670618403
Nama : Titan Hafizh Surya Kusuma
HADIR

**Comment by RendiWinurdani** [comment]
Nim : 6706184084
Nama : Rendi Winurdani
HADIR

**Comment by annisanurfauziyah** [comment]
6706184099 - Annisa Nur Fauziyah - HADIR

**Comment by winadarma** [comment]
NIm     : 6706184107
Nama  : Wina Darma Rahmah
HADIR

**Comment by dewaadityaarmanda** [comment]
Nim : 6706184004
Nama : Dewa Aditya Armanda
HADIR

**Comment by ShakilaZahraP** [comment]
Nim : 6706184103
Nama : Shakila Zahra Previa
HADIR

**Comment by miaanjani** [comment]
6706184111 - Mia Anjani Darojatun Salam - HADIR

**Comment by haidarrp** [comment]
Nim: 6706180130
Nama: Haidar Rasyid Ramdana Putra
HADIR

**Comment by indraazimi** [comment]
Yang punya masalah ketika mencoba materi Udacity/CodeLabs, silahkan klo mau bertanya.. Di sini kita **bukan cuman absen**, tapi untuk menyelesaikan masalah praktik yang kalian punya juga 😄

**Comment by RendiWinurdani** [comment]
baik pakkk

**Comment by titanhafizh** [comment]
siap pak

**Comment by banyunurwishal** [comment]
Nim : 6706184075
Nama : Banyu Nurwishal Luthfiansyam
HADIR

**Comment by MaulidiyahZuhdi** [comment]
Nim   : 6706184011
Nama :  MAULIDIYAH ZUHDI 
HADIR

**Comment by sheillya** [comment]
Nim : 6706184053
Nama : St Sheillya Pradina Satria
HADIR

**Comment by indraazimi** [comment]
Yang punya masalah ketika mencoba materi Udacity/CodeLabs, silahkan klo mau bertanya.. Di sini kita **bukan cuman absen**, tapi untuk menyelesaikan masalah praktik yang kalian punya juga 😄

**Comment by irgiahmadm** [comment]
Nim : 6706180041
Nama : Irgi Ahmad Maulana
HADIR

**Comment by Nurilfebris** [comment]
Nim :6706180126
Nama :Nuril febri setiyawan
HADIR

**Comment by fikri0511** [comment]
NIM : 6706181071
Nama : Muhammad Fikri Fadilah
HADIR

**Comment by KharisZakaria** [comment]
NIM : 6706180122
Nama : Kharis Zakaria
HADIR

**Comment by FadilIlhamm** [comment]
Nim : 6706184018
Nama : Fadil Ilham Muharram
HADIR

**Comment by naufal7567** [comment]
Nim : 6706181022
Nama : Muhammad Naufal Rabbani
HADIR

**Comment by transylvanioalfza** [comment]
Nim : 6706184118
Nama : M Transylvanio Alfarezha
HADIR

**Comment by azmirizkifar20** [comment]
NIM : 6706184055
Nama : Muhamad Azmi Rizkifar
HADIR

**Comment by Azizalfauzi** [comment]
NIM :6706180067
Nama :Aziz Alfauzi
HADIR

**Comment by indraazimi** [comment]
Btw, bagi yang bilang HADIR, tapi nggak masukin TP sesuai deadline (sebelum jam praktikum dimulai), maka **kehadirannya BATAL** ya.. Jurnalnya nanti juga **NGGAK DINILAI**. Karena TP adalah syarat mengikuti praktikum.

**Comment by AnderaFamuzia** [comment]
NIM :6706184034
Nama :Muhamad Andera Famuzia
HADIR

**Comment by Sayyid01** [comment]
NIM : 6706181063
Nama : Naufal Sayyid Furqoon
HADIR

**Comment by irgiahmadm** [comment]
> Btw, bagi yang bilang HADIR, tapi nggak masukin TP sesuai deadline (sebelum jam praktikum dimulai), maka **kehadirannya BATAL** ya.. Jurnalnya nanti juga **NGGAK DINILAI**. Karena TP adalah syarat mengikuti praktikum.

sudah di upload kemarin pak

**Comment by dickymujantara** [comment]
NIM : 6706181088
Nama : Muhammad Dicky Mujantara
HADIR

**Comment by dickymujantara** [comment]
> Btw, bagi yang bilang HADIR, tapi nggak masukin TP sesuai deadline (sebelum jam praktikum dimulai), maka **kehadirannya BATAL** ya.. Jurnalnya nanti juga **NGGAK DINILAI**. Karena TP adalah syarat mengikuti praktikum.

saya juga sudah dari kemarin pak mengumpulkan TP

**Comment by muhamadanasmustopa** [comment]
NIM : 6706184026
Nama : Muhammad Anas Mustopa
HADIR

**Comment by fhmsyhd** [comment]
NIM : 6706184097
Nama : Fahmi Imam Syuhada
HADIR

**Comment by haikalgakbar** [comment]
Nim : 6706181059
Nama : Haikal Gibran Akbar
HADIR

**Comment by ffaathirullah** [comment]
Nim : 6706181008
Nama : Fachrul Faathirulllah
HADIR
