### ISSUE TITLE
Modul 9 Connect to the Internet

### ISSUE THREAD

**Issue by cahyana78** [D3IF-Cool/diskusi-mobpro#7]
Dear all, disini akan dilakukan presensi minimal kuota.
Silahkan menuliskan NIM, Nama dan juga keterangan "HADIR" bagi mahasiswa yang sudah standby untuk praktikum

Yang punya masalah ketika mencoba materi Udacity/CodeLabs, silahkan klo mau bertanya.. Di sini kita **bukan cuman absen**, tapi untuk menyelesaikan masalah praktik yang kalian punya juga 😄

**Comment by hafidsuhanizar09** [comment]
6706183043 Hafid Suhanizar HADIR

**Comment by vironika07** [comment]
6706184105 Vironika Ayuning Tiyas HADIR

**Comment by adammaulana06** [comment]
6706184057 Adam Maulana **HADIR**

**Comment by ridhobahar1** [comment]
6706184065 Ridho Prawira Bahari **HADIR**

**Comment by literally1d** [comment]
6706180024 Wandi Yusuf Kurniawan HADIR

**Comment by shalsaazzahra11** [comment]
6706184038 Putri Shalsabilla Azzahra HADIR

**Comment by farhanshofwani1159** [comment]
6706184047 Farhan Shofwani

**Comment by ikhbalrz** [comment]
6706180124 Muhammad Ikhbal Rezanika HADIR

**Comment by farhanshofwani1159** [comment]
6706184047 Farhan Shofwani HADIR

**Comment by PutraBudiansyah** [comment]
6706184090 Putra Budiansyah HADIR

**Comment by cahyana78** [comment]
> 6706184047 Farhan Shofwani

HADIR nya belum Farhan...

**Comment by ahmadaamin12** [comment]
6706184078 Ahmad Amin HADIR

**Comment by farhanshofwani1159** [comment]
itu bu udah hehe, maaf gak ke ketik

**Comment by MuhammadArifin22** [comment]
Muhammad Arifin 6706184128 "HADIR"

**Comment by farhanshofwani1159** [comment]
Itu udah bu, maaf gak ke tulis hehe

**Comment by andibajangnurulizza** [comment]
Andi Bajang Nurul Izza 6706184134 HADIR

**Comment by indraazimi** [comment]
Yang punya masalah ketika mencoba materi Udacity/CodeLabs, silahkan klo mau bertanya.. Di sini kita **bukan cuman absen**, tapi untuk menyelesaikan masalah praktik yang kalian punya juga 😄

**Comment by deltaputrii** [comment]
6706184109 Delta Putri Dewanda HADIR

**Comment by cahyana78** [comment]
> Itu udah bu, maaf gak ke tulis hehe

Oke :)

**Comment by nurhidayahputeri** [comment]
6706184101 Nurhidayah Puteri HADIR

**Comment by ahmadridhoiwananda** [comment]
6706184020 Ahmad Ridho Iwananda HADIR

**Comment by Farhancaandra** [comment]
6706184132 Farhan candra nugraha HADIR

**Comment by literally1d** [comment]
@cahyana78 @indraazimi Saya izin bertanya, bu/pak. Cara memanggil data dari internet (JSON) ke aplikasi pada bagian object dan array gimana, bu/pak?

**Comment by syahudanahatmasuni** [comment]
6706181120 HNW Syahuda Nahatmasuni HADIR

**Comment by cahyana78** [comment]
> @cahyana78 @indraazimi Saya izin bertanya, bu/pak. Cara memanggil data dari internet (JSON) ke aplikasi pada bagian object dan array gimana, bu/pak?

Manggil data dari internet pakai Retrofit, dapat output String. Nanti String nya diubah menjadi arraylist object pakai Moshi.

**Comment by indraazimi** [comment]
@literally1d, dah dijawab ya sama Bu @cahyana78. Klo mau lihat contoh kodingannya, ada di sini: https://github.com/udacity/andfun-kotlin-mars-real-estate/commit/ca30e9c1c54650d63a3cdd36009a597d48d0aca3

**Comment by literally1d** [comment]
> > @cahyana78 @indraazimi Saya izin bertanya, bu/pak. Cara memanggil data dari internet (JSON) ke aplikasi pada bagian object dan array gimana, bu/pak?
> 
> Manggil data dari internet pakai Retrofit, dapat output String. Nanti String nya diubah menjadi arraylist object pakai Moshi.

Terima kasih atas solusinya, bu @cahyana78 , pak @indraazimi .

**Comment by cahyana78** [comment]
> > > @cahyana78 @indraazimi Saya izin bertanya, bu/pak. Cara memanggil data dari internet (JSON) ke aplikasi pada bagian object dan array gimana, bu/pak?
> > 
> > 
> > Manggil data dari internet pakai Retrofit, dapat output String. Nanti String nya diubah menjadi arraylist object pakai Moshi.
> 
> Terima kasih atas solusinya, bu @cahyana78 , pak @indraazimi .

Iya, mangga, sama-sama

**Comment by indraazimi** [comment]
Btw, bagi yang bilang HADIR, tapi nggak masukin TP sesuai deadline (sebelum jam praktikum dimulai), maka **kehadirannya BATAL** ya.. Jurnalnya nanti juga **NGGAK DINILAI**. Karena TP adalah syarat mengikuti praktikum.

**Comment by milania123** [comment]
6706184002 Nanda Putri Milania HADIR

**Comment by alifiaulilalbab** [comment]
6706184077 Alifia Ulil Albab HADIR

**Comment by AdmiralPuni** [comment]
6706184061 Dany Razzaq Farino HADIR

**Comment by TLredmagic** [comment]
6706184061 Dany Razzaq Farino HADIR

**Comment by Aya1103** [comment]
Berikut teman-teman yang tidak ada TP modul 9 di halaman wikinya:
Bagus Tetuko @BagusTetuko
Dinda Anugraheni  @dindasdp
Fachran Wardi @fachranwardi10 
Arjun Iza  
Mohammad Andiez @AndiezSatria
Farhan Candra      @Farhancaandra  
Andi Bajang Nurul @andibajangnurulizza

Punten mungkin saya ada yang terlewati

**Comment by andibajangnurulizza** [comment]
punten kak, brikut link tp saya
https://github.com/andibajangnurulizza/TP-modul-9/wiki

**Comment by Aya1103** [comment]
> punten kak, brikut link tp saya
> https://github.com/andibajangnurulizza/TP-modul-9/wiki

okee, selanjutnya TP dibuat di halaman wiki ya, tinggal tambah halaman, bukan buat repo baru

caranya bisa diliat di link berikut: https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages

**Comment by cahyana78** [comment]
Rikki Valentino
M. Pinki Adjis
Fahmi Aji

Tidak ada?

**Comment by Aya1103** [comment]
> Rikki Valentino
> M. Pinki Adjis
> Fahmi Aji
> 
> Tidak ada?

ada, kecuali yg disebutkan TP nya ada^^

**Comment by rikkylingga55** [comment]
6706180032 Rikky Valentino Lingga HADIR

**Comment by cahyana78** [comment]
> > Rikki Valentino
> > M. Pinki Adjis
> > Fahmi Aji
> > Tidak ada?
> 
> ada, kecuali yg disebutkan TP nya ada^^

Oke, tapi belum absen disini ya Aya (kecuali Rikky barusan)
Maaf ambigu...

**Comment by Aya1103** [comment]
> > > Rikki Valentino
> > > M. Pinki Adjis
> > > Fahmi Aji
> > > Tidak ada?
> > 
> > 
> > ada, kecuali yg disebutkan TP nya ada^^
> 
> Oke, tapi belum absen disini ya Aya (kecuali Rikky barusan)
> Maaf ambigu...

yaa bu

**Comment by muhamadadjis2** [comment]
6706180073 M Pinki Adjis HADIR

**Comment by fachranwardi10** [comment]
6706184001 Fachran Setiawan Wardi HADIR

**Comment by fhmbyn** [comment]
6706184095 FAHMI AJI BAYYAN DHIYA HADIR
