### ISSUE TITLE
Praktikum modul 9: Connect to the Internet

### ISSUE THREAD

**Issue by indraazimi** [D3IF-Cool/diskusi-mobpro#9]
Praktikum kali ini kita akan coba melakukan **sesi interaktif minim kuota** melalui diskusi via issue Github. Bagi yang sudah siap praktikum di komputer/laptopnya masing-masing, harap absen terlebih dahulu.

Format:
NIM - Nama - HADIR. Pertanyaan terkait materi (jika ada)

Contoh:
6706170000 - Indra Azimi - HADIR. Tidak ada pertanyaan, karena penjelasan Udacity sudah cukup.

**Comment by dinditaufa** [comment]
6706184131 - Aufa Aninditya Ramadhan - HADIR. Bagaimana cara mengaplikasikan Parcelable di Kotlin yang baik dan benar?

**Comment by aristrisnawan** [comment]
6706184056 - Aris Trisnawan - HADIR. Tidak ada pertanyaan

**Comment by bayusalam** [comment]
6706184046 - Muh Yunus Bayusalam - HADIR. Tidak ada pertanyaan

**Comment by rynzler07** [comment]
6706184119 - Fauzian Pradana Putra - HADIR. Tidak ada pertanyaan.

**Comment by cutsyarifaa** [comment]
6706184012 - Cut Syarifa Alia - HADIR. Tidak ada pertanyaan

**Comment by wandaalifia** [comment]
6706180054 - Wanda Alifia - HADIR. Tidak ada pertanyaan

**Comment by sekarns** [comment]
6706184035 - Sekar Nawang Sukma - HADIR. Tidak ada pertanyaan

**Comment by Arzuto** [comment]
6706184098 - Muhammad Arya Dhafa Rodial Widi - HADIR. Tidak ada pertanyaan

**Comment by didiarish** [comment]
6706184089 - I Komang Arishaldy P V - HADIR. Tidak ada pertanyaan

**Comment by fresyams** [comment]
6706184104 -  Fresya Maharani Sentosa- HADIR, tidak ada pertanyaan

**Comment by BasariResha** [comment]
6706181050 - Basari Resha - HADIR, Tidak ada pertanyaan

**Comment by irfanmaulanasidiq** [comment]
6706184010-Irfan Maulana Sidiq-HADIR.Tidak ada pertanyaan

**Comment by fattahazzam** [comment]
6706184036 - Azzam Fattahulhaq Santoso - HADIR. Tidak ada pertanyaan

**Comment by alfathgandhi** [comment]
6706180093 - Alfath Gandhi - HADIR Tidak ada pertanyaan

**Comment by SyahrulRamadhani21** [comment]
6706184068 - Syahrul Ramadhani - HADIR Tidak ada pertanyaan

**Comment by weslysiallagan04** [comment]
6706181081 - Wesly Siallagan - HADIR. Tidak ada pertanyaan

**Comment by rdfariz** [comment]
6706184127 - Raden Fariz Insan P - HADIR. Tidak ada pertanyaan

**Comment by bagusizzanm** [comment]
6706180060 - Muhammad Bagus Izzan Muafy - HADIR Tidak ada pertanyaan

**Comment by adniasalsabila** [comment]
6706184133 - Adnia Salsabila Ilham - HADIR. Belum ada pertanyaan

**Comment by isubhakti** [comment]
6706181023- Muhammad Imam Subhakti - HADIR. Belum ada pertanyaan

**Comment by suryatrisna** [comment]
6706180027 - Surya Trisna Pratama - HADIR, Tidak ada pertanyaan

**Comment by SaidSamaludin** [comment]
6706184042 - Said Samaludin - HADIR fitur experimental Kotlin itu apa ya  ?

**Comment by indraazimi** [comment]
> 
> 
> 6706184131 - Aufa Aninditya Ramadhan - HADIR. Bagaimana cara mengaplikasikan Parcelable di Kotlin yang baik dan benar?

@dinditaufa caranya dengan meng-implement kelas `Parcelable`, lalu membuat method2 yang diharuskan seperti `writeToParcel` dan `describeContents`. Setelah itu baru kita membuat companion object `CREATOR` nya. Contoh bisa lihat di sini: [Easy Parcelable in Kotlin](https://medium.com/the-lazy-coders-journal/easy-parcelable-in-kotlin-the-lazy-coders-way-9683122f4c00)

**Comment by rahmithamn** [comment]
6706184100 - Rahmitha Mahrul Nisa - HADIR. Belum ada pertanyaan

**Comment by indraazimi** [comment]
> 
> 
> 6706184042 - Said Samaludin - HADIR fitur experimental Kotlin itu apa ya ?

@SaidSamaludin, anotasi `@Parcelize` merupakan salah satu contoh fitur eksperimental di Kotlin. Mengapa kita sebaiknya tidak menggunakan fitur eksperimental? Jawabannya ada di sini: "_... is experimental in Kotlin 1.3. This means that in future releases it **may be changed** in ways that make it **incompatible**._"

**Comment by Dzaksp93** [comment]
6706184115 - Dzaki Ahmad - HADIR. Belum ada pertanyaan

**Comment by indraazimi** [comment]
Btw, buat semua, berhubung jam sesi teorinya dah habis, klo masih ada pertanyaan, silahkan lanjut ke asprak ya! Asprak insya Allah standby di sini sampai jam 16:30.

**Comment by dinditaufa** [comment]
Request Error: java.io.IOException: Cleartext HTTP traffic to dif.indraazimi.com not permitted

Itu error nya kenapa ya kak ?

**Comment by zikrullah79** [comment]
> Request Error: java.io.IOException: Cleartext HTTP traffic to dif.indraazimi.com not permitted
> 
> Itu error nya kenapa ya kak ?

pake https ya

**Comment by dinditaufa** [comment]
https://dif.indraazimi.com/miwok.json begitu kak ? itu juga berlaku buat img nya juga kah ?

**Comment by zikrullah79** [comment]
> https://dif.indraazimi.com/miwok.json begitu kak ? itu juga berlaku buat img nya juga kah ?

ya dicoba2 aja dulu, biar terlatih nyari error . kalo mau tetep pake http juga bisa sih. caranya ini : 
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by dinditaufa** [comment]
Sekarang ini kak 
Request Error: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Itu kenapa ya ? udah nyoba cari di stackoverflow juga gabisa

**Comment by indraazimi** [comment]
@dinditaufa ini dah dibahas di kelas sebelumnya. Coba diintip dulu issue mereka :smile:

**Comment by dinditaufa** [comment]
Sudah pak Terimakasih

**Comment by zikrullah79** [comment]
kita tutup ya praktikum kali ini, dipelajari lagi udacitynya untuk modul2 kedepannya, dan jangan lupa #diRumahAja. terima kasih.
